### ISSUE TITLE
autoClearSearch Doesn't Work

### ISSUE THREAD

**Issue by pablochud** [optimistex/ngx-select-ex#100]
After choose item from dropdown list, seach field doesn't clear. Where is the problem? 
<ngx-select [multiple]="true" [items]="locations" autoClearSearch="true" optionValueField="id" optionTextField="name" placeholder="Choose well" formControlName="location"></ngx-select>

 ngx-select-ex: 3.3.12,
 angular 5,

**Comment by galvakojis** [comment]
![screenshot from 2018-09-27 17-19-50](https://user-images.githubusercontent.com/17315578/46152379-91ef2380-c279-11e8-80af-a65e415f9c89.png)
only single values, can't use it on multiple

**Comment by oleksii-pimenov** [comment]
Try [autoClearSearch]="true" instead of autoClearSearch="true"

**Comment by pablochud** [comment]
Unfortunately, Can't bind to 'autoClearSearch' since it isn't a known property of 'ngx-select'.

**Comment by optimistex** [comment]
@pablochud I can't to reproduce the issue: https://stackblitz.com/edit/ngx-select-ex-issues-100?embed=1&file=app/app.component.ts
