### ISSUE TITLE
tried to implement a searchCallback function but not working

### ISSUE THREAD

**Issue by xyrintech** [optimistex/ngx-select-ex#102]
I have gone through all the details over this thread - https://github.com/optimistex/ngx-select-ex/issues/39 and I believe there is a way we can customise the search callback. 

Would it be possible to share an example for this?

**Comment by SachaGUILHAUMON** [comment]
In your component HTML:
`<ngx-select
                  [items]="myItems"
                  [searchCallback]="this.search"
      ></ngx-select>`

In your component TS:
`public search(search: string, item: INgxSelectOption): boolean {return true;}`

**Comment by aluxen** [comment]
This works for me, thanks!

**Comment by APet74** [comment]
I have this working on a few pages, but I have another page that has identical code for the ngx-select but gets the following error:

`core.js:12501 ERROR TypeError: _this.searchCallback is not a function
    at filterOption (ngx-select-ex.js:492)`

On both pages I have:  `  public search(search: string, item: INgxSelectOption): boolean { return true; }` but on one page it doesn't seem to be recognized. See gifs below... 

Working page: [Gif](https://i.imgur.com/dccU5Vn.gif)

Broken page: [Gif2](https://i.imgur.com/x6GXVW7.gif)

Both pages have the following in the html:
`                        <ngx-select style="width:100%" [allowClear]="true" [searchCallback]="this.search" [items]="customerListDropdown" [multiple]="false" optionValueField="CUSTOMER_ID" optionTextField="CUSTOMER_NAME" formControlName="cSearch" (typed)="searchTyped.next($event)" autocomplete="new-password" (selectionChanges)="onCustomerDropDownSelect($event)"></ngx-select>`

I promise both pages have: `  public search(search: string, item: INgxSelectOption): boolean { return true; }` I just don't know why it isn't hit in the second one.

**Comment by optimistex** [comment]
Seems it has solved :)
