### ISSUE TITLE
HTML Tags appear in Search Results

### ISSUE THREAD

**Issue by Joseph-Gage** [optimistex/ngx-select-ex#107]
When there is HTML in my items which I put in the dropdown, the HTML is highlighted in search results. I implemented a search callback to not consider HTML when matching but if the rest of the item matches a search term then if the HTML also contains that search term it shows up.

![capture](https://user-images.githubusercontent.com/13853772/43631581-df72d53a-9703-11e8-98e9-35ebd64bea64.PNG)

**Comment by gastondisacco** [comment]
Hello, I'm experiencing the same issue, any workarounds / suggestions about it? Thanks!

**Comment by optimistex** [comment]
@Joseph-Gage @gastondisacco 
Hello!
Try to do it as in the example:
https://optimistex.github.io/ngx-select-ex/
![image](https://user-images.githubusercontent.com/11228640/57680810-2191e880-7637-11e9-9a67-a63c4672e307.png)
