### ISSUE TITLE
"No Results Found" Message

### ISSUE THREAD

**Issue by Schillysrh** [optimistex/ngx-select-ex#11]
Would it be possible to add in a message for when no results are found in the search? 

My drop down is populated using an API response which delays populating, so attempting to implement this myself has resulted in clobbering the behavior of the drop down.

**Comment by optimistex** [comment]
Nice idea.
Wait for it in a next release.

**Comment by optimistex** [comment]
It's done: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.6
Check the demo: https://optimistex.github.io/ngx-select-ex/

**Comment by Schillysrh** [comment]
Thank you for this addition! 

Would it be possible to also check for presence of any user input as well as filtered results before displaying the message? I'm encountering a use case where the message appears on input focus when items is empty.

**Comment by optimistex** [comment]
What the case?
I tried to set focus to an empty select by the Tab's key, but I don't see the bug.
Help me to reproduce it.

**Comment by Schillysrh** [comment]
My ngx-select is initialized with no values in the items. I wait for a "typed" event and then I send the user input to my API, and populate items with the parsed API response. When I click into the input to start typing, I get "No Results"

component.html: 
``` html
<ngx-select [multiple]="true"
                [noAutoComplete]="true"
                placeholder="Recognize Someone!"
                [items]="items"
                [(ngModel)]="ngxValue"
                (typed)="findPerson($event)"
                (ngModelChange)="personSelect()">
</ngx-select>
```

component.ts:
``` typescript
items: any[] = [];
ngxValue: any = [];

  findPerson(input) {
        if (input.length > 0) {
            this.getPeopleFromService(input);
        }
    }
```

![ngx-select-empty-items](https://user-images.githubusercontent.com/10135351/35995520-3a684322-0cd9-11e8-8226-26209048c216.JPG)

**Comment by optimistex** [comment]
Now it's clear.
Would you like to show the "No results found" only for non-empty items? I mean to show the message only when the items contain some items but all of them are filtered?
I think it is maybe useful.

**Comment by Schillysrh** [comment]
I think that scenario makes sense!

**Comment by optimistex** [comment]
@Schillysrh Accepted. I'll do it a little later.

**Comment by optimistex** [comment]
It's done!

**Comment by optimistex** [comment]
Developing that idea continues here: https://github.com/optimistex/ngx-select-ex/issues/18
