### ISSUE TITLE
ngx-select-ex change border color according to validation fire

### ISSUE THREAD

**Issue by rvvpatel** [optimistex/ngx-select-ex#115]
Hi, I am using ng-select-ex. How to change border color on validation fire on submit form. I am using ReactiveFormsModule validation.

**Comment by FranLopezFreelance** [comment]
Did you find any solution? I have the same problem

**Comment by optimistex** [comment]
@FranLopezFreelance Use the CSS classes in order to customize the colors: https://github.com/optimistex/ngx-select-ex#styles-and-customization
