### ISSUE TITLE
[Multiple] Add a selected element programmatically

### ISSUE THREAD

**Issue by TomMenga** [optimistex/ngx-select-ex#116]
Hi,
I'm using your component in my app and I have to thank you for the time that you save me.
My use case is pretty simple, if the element typed from the user doesn't exist, i need to add and select it automatically.
I had no problem with the adding, but i can't find a way to select the new item created programmatically.
I've tried different approach ma none of them seems to work.
Am I missing something? 

Thank you for your time,
Tom

**Comment by GazousGit** [comment]
See my issue ;-)
#150
