### ISSUE TITLE
update rxjs to 6.3.3 ngx-select issue

### ISSUE THREAD

**Issue by ashishyadav23** [optimistex/ngx-select-ex#118]
### rxjs_Observable__WEBPACK_IMPORTED_MODULE_5__.Observable.from is not a function
    at NgxSelectComponent.push../node_modules/ngx-select-ex/esm5/ngx-select-ex.js.NgxSelectComponent.optionsFilteredFlat

Hello i have update angular version from 6 to 6.1 and updated rxjs ngx-select is not working and showing error something above please reply asap
<ngx-select [items]="stateList" aria-placeholder="state" name="state" placeholder="Select State" formControlName="present_address_state_id"
                    (open)="stateFocus()">
                  </ngx-select>

**Comment by optimistex** [comment]
Done!
