### ISSUE TITLE
Multi selections are always sorted in alphabetical order.

### ISSUE THREAD

**Issue by galvakojis** [optimistex/ngx-select-ex#121]
i think you should give an option to remain selection in order as user selected it, because now it always regroup in alphabetical order.

**Comment by galvakojis** [comment]
i see that is not alphabetical, but some how it depend on [items]
so if user selects: 5,2,1 it should stay 5,2,1 and now it is  1,2,5

**Comment by optimistex** [comment]
@galvakojis Fixed: https://github.com/optimistex/ngx-select-ex/releases/tag/3.6.3
