### ISSUE TITLE
in IE11,  'Enter' key couldn't activate the widget, Up / Down arrow key couldn't move between the selections

### ISSUE THREAD

**Issue by jeffli** [optimistex/ngx-select-ex#124]

**Comment by jackiewang5566** [comment]
Yeah, I have the same issue when using arrow key to navigate dropdown options on IE11, is there workaround for this one? If I press F7, enabled caret browsing after tabbing to the dropdown options I can use the up/down arrow key to navigate and press enter to select different dropdown options.

**Comment by optimistex** [comment]
Try to change options by INgxSelectOptions: https://github.com/optimistex/ngx-select-ex/blob/f87f33604cc715633219081aa30a04f3af8ee867/src/app/lib/ngx-select/ngx-select.interfaces.ts#L27-L50

How to use (from the doc):
```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import { NgxSelectModule, INgxSelectOptions } from 'ngx-select-ex';

const CustomSelectOptions: INgxSelectOptions = { // Check the interface for more options
    optionValueField: 'id',
    optionTextField: 'name'
};

@NgModule({
  imports: [BrowserModule, NgxSelectModule.forRoot(CustomSelectOptions)],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```

If you will foud better options, let me know. Probably I'll change the default options.

**Comment by jeffli** [comment]
Hi optimistex, the issue was about in IE 11, I can't use the keyboard to interact with the 'ngx-select-ex' widget, such as when I tab onto it, can't use 'enter' key to open; after some search results show up as  dropdown options, can't use up/down key to move around and select. All these keyboard operations work in Chrome and FF.  

I couldn't see how the example code you listed would resolve those issues.

**Comment by satjai1** [comment]
Any solution for this question?

**Comment by satjai1** [comment]
Surely, I can contribute in this project. I'm currently blocked in my organization's project where this plugin is being used & production release is quite close. Let me sort out some time for this.
