### ISSUE TITLE
[defaultValue] with remote data

### ISSUE THREAD

**Issue by mdhilwan** [optimistex/ngx-select-ex#128]
Is there a way for the [defaultValue] be used together with subscription type service instead of a pre-populated list?

**Comment by optimistex** [comment]
@mdhilwan Check example on the tests:
https://github.com/optimistex/ngx-select-ex/blob/f87f33604cc715633219081aa30a04f3af8ee867/src/app/lib/ngx-select/ngx-select.component.spec.ts#L190
