### ISSUE TITLE
Error on disabled option with an empty array

### ISSUE THREAD

**Issue by BBellenoue** [optimistex/ngx-select-ex#13]
Hi,
When the initial array of item is empty, there is an error with the disabled check
`Cannot read property 'disabled' of undefined
    at NgxSelectComponent.optionActivate (ngx-select-ex.js:472)`
In this case, options is empty in the following switch `case ENavigation.first:
                    return options[0];`

**Comment by optimistex** [comment]
Fixed: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.7
