### ISSUE TITLE
Highlight and serch then enter not working properly

### ISSUE THREAD

**Issue by sufiiiyan** [optimistex/ngx-select-ex#135]
on focus select it highlights the first item
![highlight](https://user-images.githubusercontent.com/12623084/50140956-483c3500-02cc-11e9-9854-9bac1fc4df7f.png)
but when i start typing some text, highlight goes away and when i hit enter it select bydefault 1st item from select

![nohighlight](https://user-images.githubusercontent.com/12623084/50140967-4d00e900-02cc-11e9-804b-32fff1654e92.png)

"ngx-select-ex": "^3.5.2-ng4",

Node: 10.8.0
Angular: 5.2.6

**Comment by optimistex** [comment]
@sufiiiyan It seems fixed in latest version. Try it: https://stackblitz.com/edit/ngx-select-ex-issues-100-unf9rx?file=app/app.component.ts

**Comment by sufiiiyan** [comment]
How can I install latest version of "ngx-select-ex ng4"
my current version is "ngx-select-ex": "^3.5.2-ng4",

**Comment by optimistex** [comment]
@sufiiiyan Just confirm that your issue is solved in the new version.
I need to know is it a new bug and I have to find a time to fix it? Or it is a reason to update the *-ng4 version.

**Comment by sufiiiyan** [comment]
Yes the link you have sent me fixes my issue. Please update ng4 version with the same

**Comment by optimistex** [comment]
@sufiiiyan Ok. I'll try to find a time for it in the evening.

**Comment by sufiiiyan** [comment]
Thank you so much

**Comment by optimistex** [comment]
@sufiiiyan I've upgraded the ng4 compatible version.
Install: `npm i ngx-select-ex@ng4-dev`

Check it, please.

**Comment by sufiiiyan** [comment]
Awesome its working 👍 Thank you for quick support
