### ISSUE TITLE
Custom CSS Styles

### ISSUE THREAD

**Issue by chasevis** [optimistex/ngx-select-ex#136]
Hello,
First of all Thank you for your effort on this fork. 
I am trying to change the height of the .ngx-select__selected class but having no luck with that.

Any Help is appreciated

Thank you

**Comment by optimistex** [comment]
@chasevis Probably you need to change `ngx-select__toggle`

![image](https://user-images.githubusercontent.com/11228640/50404721-c0ff2d80-07b3-11e9-9a49-200285e7cb11.png)

**Comment by optimistex** [comment]
Try to add `!important`:
`.ngx-select__toggle{height: 65px !important}`

**Comment by chasevis** [comment]
no luck

**Comment by optimistex** [comment]
@chasevis Show your code.
Probably you do not included your css or something like this?
Try to change a colour to be sure that the css is included and works.

**Comment by optimistex** [comment]
@chasevis The example:
https://stackblitz.com/edit/ngx-select-ex-issues-136?file=app/app.component.ts

You should use `/deep/` if you make own css in a component.
But, `/deep/` has deprecated....

**Comment by guntram** [comment]
> You should use `/deep/` if you make own css in a component. But, `/deep/` has deprecated....

You can use encapsulation in the @Component annotation:

`@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  // ViewEncapsulation.None is the equivalent for /deep/
  encapsulation: ViewEncapsulation.None,
})`
