### ISSUE TITLE
List of issue in new version

### ISSUE THREAD

**Issue by pablochud** [optimistex/ngx-select-ex#138]
ngx-select-ex: 3.6.8,
angular 7

The three issues listed below worked in previous version and it was perfect. 
1). The onMouseEnter event doesn't retrieve properly index of item. It always returns 0;
2). Selector jumps to the first element when dynamically expand item list at the last element
3). Before it downloads the list asynchronously, it displays the message no data found . It should not display

example here:
https://stackblitz.com/edit/ngx-select-ex-issues-100-yaga6d

**Comment by pablochud** [comment]
4). The Typed event triggers when the list is being navigated by arrows, but the search field is still empty.

example above was updated.

**Comment by szymon5x** [comment]
I have fixed those problems and created a [pull request](https://github.com/optimistex/ngx-select-ex/pull/142).

**Comment by optimistex** [comment]
@szymon5x I've released a fix that touched your code:
- the issue: https://github.com/optimistex/ngx-select-ex/issues/170
- the release: https://github.com/optimistex/ngx-select-ex/releases/tag/v3.7.6

Now, seems it work better. But, please, make sure that I did not brake your logic.
