### ISSUE TITLE
Add remove event

### ISSUE THREAD

**Issue by BBellenoue** [optimistex/ngx-select-ex#14]
Would it be possible to add a remove event when clicking on the clear button (single or multiple items) ? 
Currently the blur event requires leaving the select to trigger.

**Comment by optimistex** [comment]
Maybe the `fromControl.valueChanges` can ensure your goal?
```html
<ngx-select [items]="['1111', '2222']" [fromControl]="fromControl">
```
```typescript
fromControl.valueChanges.subscribe((v) => valueChanged(v));
```
Check the DEMO: https://optimistex.github.io/ngx-select-ex/
![image](https://user-images.githubusercontent.com/11228640/35973062-152c772a-0ce5-11e8-842a-59dec0246000.png)
![image](https://user-images.githubusercontent.com/11228640/35973081-2831a200-0ce5-11e8-802b-54378c744470.png)
______
For clear. I am trying to save simple usage.
Give me the real reason for integrating `select`/`remove` events.
Describe is your case?

**Comment by optimistex** [comment]
Maybe we have to improve documentation?

**Comment by BBellenoue** [comment]
I was trying to disable another component on my page when there is no item selected. It works well with the valueChanges. By the way my close and blur event became useless in this case.

**Comment by optimistex** [comment]
And, it is mean we do not need the `remove` event anymore?

**Comment by BBellenoue** [comment]
I still think it could be nice to have the remove event as I only need close and remove event for my case.
With the valueChange my function is launch for all kind of event. But the workaround works.

**Comment by optimistex** [comment]
Implemented: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.7
Check the DEMO: https://optimistex.github.io/ngx-select-ex/
![image](https://user-images.githubusercontent.com/11228640/35977529-69f18566-0cf4-11e8-95c0-cee1e498aaee.png)
