### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by LeonadoRivaldo** [optimistex/ngx-select-ex#145]
I need to remove the search input field, it is possible to do that?

**Comment by optimistex** [comment]
@LeonadoRivaldo 

[noAutoComplete] | boolean | false | Set to true Set to true to hide the search input. This option only applies to single-value inputs

**Comment by LeonadoRivaldo** [comment]
@optimistex Thanks man, that is going to save me alot of work, im my current project! :)
