### ISSUE TITLE
SafeValue error in dropdown text with ng-tamplate

### ISSUE THREAD

**Issue by idris-rampurawala** [optimistex/ngx-select-ex#147]
Hi,
I want to truncate the long text of the dropdown with ellipses and hence I am using template to show the text
```<ng-template ngx-select-option-selected ngx-select-option let-option let-text="text"><span [tooltip]="text" placement="auto">{{text}}</span></ng-template>```

But for the above snippet, I am getting savevalue error from angular 7 
`SafeValue must use [property]=binding: user1 (see http://g.co/ng/security#xss)` 
Tried using `domsanitizer` but it did not help.

Please suggest a solution for the above.

**Comment by optimistex** [comment]
@idris-rampurawala 
The component still on Angular6. So, the general issue is upgrading the component up to Angular7. Unfortunately I can not do it in soon time because of out of the time.
Would be nice from your side to maintain the component and upgrade... Make a pull request, I'll release it.

**Comment by optimistex** [comment]
Related task #148

**Comment by idris-rampurawala** [comment]
@optimistex I was able to find a work around this issue
```
<ng-template ngx-select-option-selected ngx-select-option let-option let-text="text">
            <span [title]="option.text" placement="atuo">{{option.text | truncateStringWithEllipses: 25}}</span>
        </ng-template>
```
So, instead of using `text`, I used `option` object to achieve the requirement.
Thanks.
