### ISSUE TITLE
Clicking top row of multiselect after selecting at least one item doesn't open dropdown

### ISSUE THREAD

**Issue by craig-dae** [optimistex/ngx-select-ex#155]
**Describe the bug**
When set to multiple values, and when at least one value is selected, the selected value occupies the first line of the dropdown control, and a second line is generated. You have to click the second line of the control to open the dropdown. Clicking the first line does nothing. There is nothing to clearly indicate that this is intentional. We have customers that immediately started complaining about this.

Either make it so you can click ANYWHERE on the control to open a dropdown (except on an existing value), or make it more clear where you're supposed to click.

**To Reproduce**
Please, make an example there https://stackblitz.com/ to reproduce the bug and share a link to the example. 

https://stackblitz.com/edit/angular-5hoswh

Can't click to the right of the X

**Expected behavior**
Either make it more obvious to non-technical users where you can click, or make any area clickable.

**Comment by optimistex** [comment]
@craig-dae Thank you for follow the description requirements and the live example. Clear enough and good idea to improve.

I'll try to find a time to make this improvement in a week. Or, you can make a pull request with a fix and I'll release it.

In case you make it yourself... I think that the event `(click)="inputClick(input && input.value)"` should be added to https://github.com/optimistex/ngx-select-ex/blob/aa1d9e4d8746978eeae37a2f5fdb3ca186d2f18a/src/app/lib/ngx-select/ngx-select.component.html#L40

**Comment by craig-dae** [comment]
Looks like that works. I also dropped a `event$.stopPropagation()` to prevent the dropdown from firing when you click an existing entry. 

I plan to get you a PR today.

**Comment by craig-dae** [comment]
https://github.com/optimistex/ngx-select-ex/pull/156

**Comment by craig-dae** [comment]
@optimistex Hey, I've had the PR up for a while now. Any chance we can get it merged?

Thanks!

**Comment by optimistex** [comment]
@craig-dae Hello!
I've came back from a vacation today...
I'll release it at the evening.

**Comment by optimistex** [comment]
@craig-dae Merged into `development` branch.
To install it use `npm i ngx-select-ex@3.6.11-dev`
