### ISSUE TITLE
how to required validation do for this select box (ignoring 'Select ----' option)

### ISSUE THREAD

**Issue by yogeshCN** [optimistex/ngx-select-ex#159]
<ng-selectize [config]="citySingleSelectConfig" formControlName="City" [options]="citySingleSelectOptions"
[(ngModel)]="citySingleSelectValue" ngDefaultControl
>
citySingleSelectOptions: any = [
{
label: 'Select City',
value: '0',
},
{
label: 'Pune',
value: '1',

}, {
    label: 'Kolhapur',
    value: '2',
   
}, {
    label: 'Nasik',
    value: '3',

}, {
    label: 'Satara',
    value: '4',

}
];
how to required validation do for this select box (ignoring 'Select City' option)

**Comment by optimistex** [comment]
@yogeshCN Actually I do not know how works the component `ng-selectize`.
This issues for the `ngx-select-ex` component.
