### ISSUE TITLE
optionTextField use more than one field

### ISSUE THREAD

**Issue by lupitaflowers3** [optimistex/ngx-select-ex#16]
Hello, I have an array of objects like this:
[{"CurrencyCode":"USD","Name":"US Dollar"}]
 and i want show in the TextField both fields
it is possible i did this optionTextField="CurrencyCode + Name" but doesn't work

**Comment by optimistex** [comment]
> it is possible i did this optionTextField="CurrencyCode + Name" but doesn't work

It's have not to work.
__________
**Solution.**
Transform your array:
```typescript
let innerItems: {"CurrencyCode": string; "Name": string};
innerItems.forEach(item => item.text = item['CurrencyCode'] + item['Name']);
```

**Comment by lupitaflowers3** [comment]
This works, thank you.

**Comment by optimistex** [comment]
Look at the alternative solution: https://github.com/optimistex/ngx-select-ex/issues/19#issuecomment-364680505

**Comment by PeterBarron** [comment]
I didn't want to transform the array but found I could use <ng-template> :

**Comment by PeterBarron** [comment]
My solution above came back to bite me because the auto complete functioning of the select box doesn't work using the <ng-template> approach... I did transformed the array after all.
