### ISSUE TITLE
Add `appendTo` option

### ISSUE THREAD

**Issue by optimistex** [optimistex/ngx-select-ex#160]
The issue: https://github.com/optimistex/ngx-select-ex/issues/47#issuecomment-456470179

The solution: https://ng-select.github.io/ng-select#/append-to-element
Their code: https://github.com/ng-select/ng-select/blob/5819fc18c204fc9425c3f51ec0da9ab24feb89ff/src/ng-select/ng-dropdown-panel.component.ts

I need to find a time to implement that in ngx-select-ex.

**Comment by evyatarbh** [comment]
A year and a half after this request's creation, any update?

**Comment by adrianbrs** [comment]
More than two years later... #198 :)

**Comment by optimistex** [comment]
@evyatarbh Well done! 
Released: https://github.com/optimistex/ngx-select-ex/releases/tag/v6.1.2
