### ISSUE TITLE
Autocomplete text remains after being applied

### ISSUE THREAD

**Issue by craig-dae** [optimistex/ngx-select-ex#161]
**Describe the bug**
When typing in the autocomplete area and hitting enter, the text remains even after the appropriate dropdown item is added to the selected array. It has to be deleted before using the text input again. Users are also confused as to the effect of leaving the text.

**To Reproduce**
- Go to the demo at: https://optimistex.github.io/ngx-select-ex/
- Select `Multiple`
- Click inside the "No city selected" input area
- Type "Amster"
- Hit `enter`

Amster" stays in the text input area, and has to be deleted before using the text input again. Users are confused about whether it is necessary to delete the text before saving their form. 

**Expected behavior**
Autocomplete text should be removed when it results in adding a selected item to the array.

**Comment by optimistex** [comment]
@craig-dae Thank you for such good description. I'll check it in a while and try to fix.

**Comment by optimistex** [comment]
@craig-dae 
Use the option:

autoClearSearch | boolean | false | Auto clear a search text after select an option. Has effect for multiple = true
-- | -- | -- | --

**Comment by craig-dae** [comment]
Sorry for missing that! Thank you!
