### ISSUE TITLE
doRemove

### ISSUE THREAD

**Issue by elham-rababah** [optimistex/ngx-select-ex#164]
**Describe the bug**

**To Reproduce**
Please, make an example there https://stackblitz.com/ to reproduce the bug and share a link to the example. 

**Expected behavior**

**Comment by elham-rababah** [comment]
Sorry for the short description in the first one. 
calling doRemove function not working form the ts. 
for example on the ts I put something like this
 if (this.resetSelect) {
      this.doBlur();
      this.doRemove(this.formGroup.value[this.formControlName]);
    }}
its call the event and print to the console but the vallue still apper on the view in the other hand when u use the clear button every thing work smothly

**Comment by optimistex** [comment]
@elham-rababah 
Please, make an example there https://stackblitz.com/ to reproduce the bug and share a link to the example.

**Comment by elham-rababah** [comment]
@optimistex thanks for fast response I found my problem, Already I was used the wrong function.
I found that I should use optionRemove() function 

The solution was something like this
  @ViewChild('localRef') localRef: NgxSelectComponent;
  private loaclSelectedOption;

  if (this.resetSelect) {
      var event = new MouseEvent('click');
      this.localRef.optionRemove(this.loaclSelectedOption, event);
    }
