### ISSUE TITLE
Enhancement - Ability to change drop-down icon

### ISSUE THREAD

**Issue by idris-rampurawala** [optimistex/ngx-select-ex#165]
**Describe the bug**
There is an option to change the clear button icon, but required an option to change the drop-down icon as well. I am actually fetching the lists from server on key type event. Users does not feel intuitively that he has to start typing some characters to fetch some data from the server. Even though have added the placeholder to help them, users are not reading it! (user's do not read always)

**Expected behavior**
It would be better if we can customize the icon so I can add search icon which will be somewhat intuitive to the users. If any other way, then please let me know.

**Comment by optimistex** [comment]
@idris-rampurawala 
You can use this:
```css
.ngx-select__toggle-buttons .dropdown-toggle:after {
    border-top-color: red;
}
```
![image](https://user-images.githubusercontent.com/11228640/62297860-96c4cb00-b47a-11e9-9c1e-c1e6c6845652.png)
