### ISSUE TITLE
Custom click directive stoped working

### ISSUE THREAD

**Issue by eugene-gv** [optimistex/ngx-select-ex#166]
Added custom directive:
```
@Directive({
  selector: '[ngxSelectMultiClear]'
})
export class NgxSelectMultiClearDirective {
 @Output() ngxSelectMultiClear = new EventEmitter();

 @HostListener('click', ['$event'])
 onClick(event) {
    console.log(event)
 }
}
```
In template:

```
<ngx-select  (ngxSelectMultiClear)="customFunc()"
                        ...
></ngx-select>
```

On click - nothing happens. In 3.6.10 and previous works fine

**Comment by optimistex** [comment]
@eugene-gv Please, reproduce the issue within an example. 
Make fork from that: https://stackblitz.com/edit/ngx-select-ex-scratch

**Comment by eugene-gv** [comment]
There is integrated clear button, so no need in such directive, sorry.
But custom click on selected option don't work anyway.
 check here: https://stackblitz.com/edit/ngx-select-ex-scratch-btus6p

**Comment by optimistex** [comment]
@eugene-gv 
It works with a fix in your code: 
https://stackblitz.com/edit/ngx-select-ex-issue-166?file=src%2Fapp%2Fapp.component.html
![image](https://user-images.githubusercontent.com/11228640/62698459-dee96d80-b9e5-11e9-8b90-83c2460a1eac.png)

**Comment by eugene-gv** [comment]
![image](https://user-images.githubusercontent.com/53374505/62704192-7608f200-b9f3-11e9-9177-17b6ba8599ee.png)
I need it to work while clicking text inside selected element. Is it possible?
Now when i click anywhere inside selected element console log is not triggered

**Comment by optimistex** [comment]
@eugene-gv 
Updated: https://stackblitz.com/edit/ngx-select-ex-issue-166?file=src%2Fapp%2Fapp.component.html
![image](https://user-images.githubusercontent.com/11228640/62704857-fe3bc700-b9f4-11e9-8753-ec2c762705e3.png)

**Comment by eugene-gv** [comment]
Thanks, Konstantin!
