### ISSUE TITLE
Internet explorer 11 extended support

### ISSUE THREAD

**Issue by NikolaPeevski** [optimistex/ngx-select-ex#167]
**Describe the bug**
Currently the behaviour in Internet explorer 11 is very different from the one in other browsers such as chrome, rendering the component close to unusable. There is no scroll bar and the positioning when the window is smaller is inaccurate. I have attached two pictures one from Google Chrome with the expected behavior and one from Internet explorer. 

### Internet Explorer 11
![image](https://user-images.githubusercontent.com/14194863/62515232-6ab69a80-b82a-11e9-928f-7b1c9ec8238a.png)

### Google Chrome
![image](https://user-images.githubusercontent.com/14194863/62515248-7a35e380-b82a-11e9-9cfd-d97870b24481.png)

**To Reproduce**
No special reproduction instructions are needed. Simply load the component using Internet Explorer 11.

**Expected behavior**
The scroll bar to be usable and the positioning to be relative to both the parent and the window.
![image](https://user-images.githubusercontent.com/14194863/62515273-9043a400-b82a-11e9-9590-18ea7df4de9f.png)

**Comment by optimistex** [comment]
@NikolaPeevski As I can see, the input fields (ngx-select conponent) are much larger that on the image 1. I assume if you fix width on IE11 you will solve the issue. 

For sure it is not a general solution and would be good to add calculation of distance to right side if the document. Probably I'll do it in a future.

**Comment by NikolaPeevski** [comment]
That would add an excessive listener to the component just to recalculate the width every time the window is resized.

What about the scrollbar issue ?

**Comment by optimistex** [comment]
@NikolaPeevski 
In my mind the calculation should be done on open menu only.

Regarding the scroll bar. I believe it is there and you do not see it because of the the drop down menu is particularly out of the screen.
