### ISSUE TITLE
No option to clear if default value set

### ISSUE THREAD

**Issue by gregduffield** [optimistex/ngx-select-ex#168]
**Describe the bug**
If you set the [formControl] and a default value the X is not available and you are not able to clear the initial value.

**To Reproduce**
https://stackblitz.com/edit/ngx-select-ex-scratch-pn83au

**Expected behavior**
You should be able to clear the initial/default value.

**Comment by optimistex** [comment]
@gregduffield @gregduffield Thanks for the example. I'll check it in a while.

**Comment by optimistex** [comment]
@gregduffield Checked.
This is the idea of "default value" to keep the select list with some value.

**Comment by gregduffield** [comment]
Yes but the behaviour is different if you attach a [formControl] ? No [formControl] and you can clear, with a [formControl] you cannot clear? I would like to be able to clear with a [formControl].

This is then making the default value work as an initial value as well which can then be cleared which is really good.




Greg Duffield
Co-Founder & CTO
m: +44 7974735020
e: greg@getbrisk.com | w: www.getbrisk.com
Brisk is a trading name of Collabrotech Ltd. Collabrotech Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. This e-mail and any attachments are confidential and may also be privileged. If you are not the named recipient, please notify the sender immediately and do not disclose the contents to another person, use it for any purpose, or store or copy the information in any medium. Although this e-mail and any attachments are believed to be free from any virus or other defect which might affect any system into which they are opened or received, it is the responsibility of the recipient to check that they are virus free and that they will in no way affect systems and data. No responsibility is accepted by Collabrotech Ltd for any loss or damage arising in any way from their receipt, opening or use
Collabrotech Ltd is a company registered in England and Wales under number 11388497.
Registered office: Founders Factory Northcliffe House, Young Street, London, United Kingdom, W8 5EH, United Kingdom.

**Comment by optimistex** [comment]
@gregduffield Now I see the difference.
Seems the are bug without the formControl. The "X" should not be available at all if the default value already selected.
