### ISSUE TITLE
dropdown cut-off in Angular 4

### ISSUE THREAD

**Issue by klteograss** [optimistex/ngx-select-ex#17]
hi, I have installed ng4 version `npm i ngx-select-ex@ng4`.
However, the dropdown list is cut-off if the div is having a shorter height.  

Any solution?  Thanks!

**Comment by optimistex** [comment]
I guess the div contains style `overflow: hidden`. If it is right then it is trouble of layout. Remove the style.

**Comment by klteograss** [comment]
Unfortunately, the trick of `overflow: hidden` does not work if the select input is within a jquery dialog.

**Comment by optimistex** [comment]
I think it is just trouble of a layout.
In my project have made custom styles for modal dialogs:
![image](https://user-images.githubusercontent.com/11228640/36006858-7e9347c8-0d50-11e8-8d8e-17ee667cdd26.png)
As you see. It is can be fixed only with CSS.

**Comment by klteograss** [comment]
Modal dialog is different because it cover the document body.
A jquery dialog is embedded within the div.

**Comment by optimistex** [comment]
If your project is published then give me a link and some instructions how to achieve the dialog.
Tomorrow I'll try to suggest a solution to you.

But the main idea it is to avoid `overflow: hidden`! Because it is a behavior of the CSS rules. 
The similar topic about you trouble: https://github.com/harvesthq/chosen/issues/86

**Comment by jackiewang5566** [comment]
Is there an API that can append the dropdown to body like ng2-select appendTo, 
https://ng-select.github.io/ng-select#/append-to-element, or an input property which can set dropdown container to body? I think attach dropdown to body can fix this cutoff issue.
