### ISSUE TITLE
Once drop-down list was open component cannot be destroyed due to event listener

### ISSUE THREAD

**Issue by evyatarbh** [optimistex/ngx-select-ex#170]
The component is adding a document.onmousemove event listener using an anonymous function, so it cannot be removed and the component cannot be destroyed.
The event listener is being added [here](https://github.com/optimistex/ngx-select-ex/blob/master/src/app/lib/ngx-select/ngx-select.component.ts#L504)
While debugging our application, I noticed this event listener is being constantly triggered, even after the parent component did not appear on the DOM anymore (which made Angular throw an error).

**Comment by optimistex** [comment]
Good catch! I'll fix it in a while...

**Comment by optimistex** [comment]
@evyatarbh Fixed: https://github.com/optimistex/ngx-select-ex/releases/tag/v3.7.6
