### ISSUE TITLE
How to determine if the control is touched

### ISSUE THREAD

**Issue by mamwadei** [optimistex/ngx-select-ex#171]
I am trying to do some code when the control is touched but it seems not work. How to do that please ?

**Comment by optimistex** [comment]
@mamwadei Make an example on stackblitz. I'll check and fix

**Comment by mamwadei** [comment]
when I am trying to make validation when the control is touched but not working while it works fine with the controls in the same form also dirty works only when I select one option and then clear it and not working if I type anything for search

**Comment by optimistex** [comment]
@mamwadei Please, use https://stackblitz.com/
to reproduce and show the bug.

I will help much enough to understand faster and as result fix it faster.

Thanks.

**Comment by guntram** [comment]
ng-touched is set after something was selected:
https://stackblitz.com/edit/angular-7-template-driven-form-validation-nhzoet

**Comment by optimistex** [comment]
@guntram @mamwadei 
Seems it works fine: https://stackblitz.com/edit/angular-7-issues-171?file=app/app.component.ts
