### ISSUE TITLE
Render options selected from API

### ISSUE THREAD

**Issue by josevsp** [optimistex/ngx-select-ex#172]
I am trying to do an update form and I can't render the chips or options from my backend.
How can I render the selected options with [multiple] and dynamic data?

this is my example:
````
 <ngx-select
     class="classes"
     required
     [multiple]="true"
     [items]="atributos"
     optionValueField = "codigo_atributo"
     optionTextField = "nombre_atributo"
     [(ngModel)]="atributosSelected"
     [autoClearSearch]="true"
     placeholder="Ningún atributo seleccionado"
     (selectionChanges)="doSelectAtributos($event)"
     [ngClass]="{ 'is-invalid': submitted && f.select_atributos.errors }"
     [ngModelOptions]="{standalone: true}"
     [defaultValue]="atributosSelected">
</ngx-select>
````

I am using Angular 7+. 

Thanks a lot.

**Comment by optimistex** [comment]
@josevsp Please, make an example on stackblitz.com

**Comment by josevsp** [comment]
https://stackblitz.com/edit/angular-xfbkbo

There I put an example

**Comment by josevsp** [comment]
any answer for this issue?

**Comment by optimistex** [comment]
@josevsp I did not get what exact issue do you have...
If it is about styles, you can use `bootstrap.css`: https://stackblitz.com/edit/angular-issues-172?file=src/styles.css
![image](https://user-images.githubusercontent.com/11228640/69267175-5037df80-0bd5-11ea-82b5-7a7368f60aca.png)

**Comment by josevsp** [comment]
@optimistex I want to set as default some multi-values loaded from the array, but I didn't find any way to set my default options.

I thinked that setting thats values in the ngModel variable would do it it but it isn't happened
``
this.atributosSelected.push(data.results[0]);
``      

Then I try with selector [defaultValue] and also not work.
``
    [defaultValue]="atributosSelected"
``

How can i set default objects in select multi?

**Comment by optimistex** [comment]
@josevsp Ok, got it.
Fixed the example: https://stackblitz.com/edit/angular-issues-172?file=src%2Fapp%2Fapp.component.ts

1. The array of default values has to have just IDs that you defined in `optionValueField` 
2. It would be better to use `formControl`. I added an example for you.
