### ISSUE TITLE
Manipulate the selected content in ngx-select [multiple]

### ISSUE THREAD

**Issue by JeyashreeA** [optimistex/ngx-select-ex#175]
I am trying to using the "ngx-select-ex" library for selecting multiple options from a drop-down. When more than 3 items are selected, I would like the selected items to show up as " Selected".

I understand that in case of single select, we can manipulate the template by using the "ngx-select-option-selected" directive. But I cant seem to get the expected result in case of multi select. All the selected values become "4 Selected" when the number of selected options become more than 3.

What would be the appropriate way to achieve this behaviour?

**Comment by optimistex** [comment]
@JeyashreeA Sorry, but I read twice and did not get your idea.

It works like that: 
https://optimistex.github.io/ngx-select-ex/
![image](https://user-images.githubusercontent.com/11228640/72904979-6fb7c980-3d38-11ea-8dee-c37cb2bd63fa.png)

Could you, draw your idea to show on a picture what exactly do you want to do?
Also, you could update the playground to express your idea: https://stackblitz.com/edit/angular-issues-172

**Comment by JeyashreeA** [comment]
Hi @optimistex ,

Sorry for not being very clear. The behaviour that I am trying to achieve is as below:

When a predefined minimum value of elements are selected, I would like to see their names as such.
![Screenshot 2020-01-23 at 12 07 51 PM](https://user-images.githubusercontent.com/10459265/72962068-4733dc00-3dd9-11ea-9c49-4b555141e65d.png)

However, once they exceed this limit, it would be great to see as below (4 selected) in the selected options.
![Screenshot 2020-01-23 at 12 08 14 PM](https://user-images.githubusercontent.com/10459265/72962131-76e2e400-3dd9-11ea-83e8-a584fa89c14b.png)
 
I have updated what I tried with the library here - [https://stackblitz.com/edit/angular-issues-172-nz655h](https://stackblitz.com/edit/angular-issues-172-nz655h). I used the "ngx-select-option-selected" for this. I understand that the directive is to manipulate each option individually and there are also other flaws here such as the clear option inside each selected option pill. So I was hoping if you would help me understand if we would just somehow group them up to show them as a collective entity.

Please let me know if I haven't been clear. Thanks!

**Comment by optimistex** [comment]
@JeyashreeA Try this: https://stackblitz.com/edit/angular-issues-175-2
Generally, the components does not support your idea. However, you can make a wrapper to add the functionality.

**Comment by JeyashreeA** [comment]
@optimistex  I understand the component doesnt support the idea. I realised that too. Thanks for the help... I had a similar idea and made that change too!

I am closing the ticket now.
