### ISSUE TITLE
How to preserve option templates when Dynamically Created

### ISSUE THREAD

**Issue by bmgarness** [optimistex/ngx-select-ex#177]
**Describe the bug**
When Dynamically creating the ngx-select-component, I do not know how to set the template for Options. 

**To Reproduce**
Here's an example

https://stackblitz.com/edit/ngx-select-ex-scratch-fnrbs5

**Expected behavior**

I expected the template underneath ngx-select with the right directive to be also created.

**Comment by optimistex** [comment]
@bmgarness In your approach most probably this article could help you: https://blog.ng-book.com/dynamic-components-with-content-projection-in-angular/

Also, you could use `*ngFor` to produce new components. Usually I do this

**Comment by optimistex** [comment]
@bmgarness I've prepared an example for you for producing the select components via *ngFor:
https://stackblitz.com/edit/ngx-select-ex-scratch-issues-177?file=src/app/app.component.html
