### ISSUE TITLE
Setting up "No Results Found" message

### ISSUE THREAD

**Issue by BBellenoue** [optimistex/ngx-select-ex#18]
Hi,
In order to be able to manage several languages, is it possible to change the default text for `NO RESULTS FOUND` which in addition is capitalized? 
Thanks.

**Comment by optimistex** [comment]
I have an idea to implement this via service of options.

In final you will be able to set up like this:
```typescript
// ngx-select-custom-option.ts
import {ToastOptions} from 'ng2-toastr';

export class NgxSelectCustomOption extends NgxSelectOptions {
  noResultFoundMessage = 'Список пуст'; // you can override any options available
}

// app.module.ts
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import { NgxSelectModule } from 'ngx-select-ex';
import { NgxSelectCustomOption } from './ngx-select-custom-option';

@NgModule({
  imports: [BrowserModule, NgxSelectModule],
  declarations: [AppComponent],
  providers: [ 
    {provide: NgxSelectOptions, useClass: NgxSelectCustomOption},
  ],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```
**What do you think about the idea?**
The idea borrowed there: https://github.com/PointInside/ng2-toastr

**Comment by optimistex** [comment]
Currently, implemented templates: https://github.com/optimistex/ngx-select-ex#templates
Try to customize the "NO RESULTS FOUND" within the `ngx-select-option-not-found` template.

**Comment by BBellenoue** [comment]
Nice, it's easier to implement. Why is it in uppercase by default ?

**Comment by optimistex** [comment]
No, it is not:: https://github.com/optimistex/ngx-select-ex/blob/d2d785703a92215cefccaf97889d9636f70dcdab/src/app/lib/ngx-select/ngx-select.component.html#L105

**Comment by BBellenoue** [comment]
I have only this
` <ngx-select
    [items]="availableDepartements"
    [(ngModel)]="selectedDepartements">
    <ng-template ngx-select-option-not-found>
      No dept found
    </ng-template>
  </ngx-select>`

And my result looks like :
NO DEPT FOUND

**Comment by optimistex** [comment]
May be are you have a wrong css?
Check the demo. It has no the effect.

**Comment by BBellenoue** [comment]
It works, thanks.

**Comment by optimistex** [comment]
Solved! Check the release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.0
