### ISSUE TITLE
Two-way binding with NgModel Not working on update

### ISSUE THREAD

**Issue by JeyashreeA** [optimistex/ngx-select-ex#181]
Hi,

I am using the component in a page where the items listed by the drop down change based on other UI inputs/ actions. Please find a similar scenario [here](https://stackblitz.com/edit/angular-issues-172-sewb69). When I click on the button, the items that are listed updates and am ensuring to update the ngModel value with a value from the newly generated list.

However, even though the value is assigned programatically, the UI doesn't show this change - as seen from the example.

Can you help me figure out why this happens? TIA.

**Comment by optimistex** [comment]
@JeyashreeA I'll be able to check and answer in a week after my vacation

**Comment by optimistex** [comment]
@JeyashreeA 

1.  You forgot to take the `name`:
bad `this.atributosSelected = this.atributos[2]`
good `this.atributosSelected = this.atributos[2].name`

2. To avoid some issues wrap it into `setTimeout` or use FormControl:
`setTimeout(() => this.atributosSelected = this.atributos[2].name, 0);`
