### ISSUE TITLE
ngx-select default value is not working for array object

### ISSUE THREAD

**Issue by abdelbaki** [optimistex/ngx-select-ex#187]
Hello,
I want to define a default value for ng-select, it work fine for array of string. But not when i use a array of object.

this is my example :
https://stackblitz.com/edit/angular-issues141-md6trm?file=src/app/app.component.ts

**Comment by optimistex** [comment]
@abdelbaki The default value should have values defined in `optionValueField` (id by default). It won't accept anything else and shouldn't.
So, in your example update:
```typescript
tap(items => this.select.setValue(items[0]))
```
to:
```typescript
tap(items => this.select.setValue(items[0] && items[0].id))
```

And it will work fine.
