### ISSUE TITLE
Not working with custom getter

### ISSUE THREAD

**Issue by ZhukV** [optimistex/ngx-select-ex#19]
Hi.  I have a problem with custom getter and use the `optionTextField`

I have a custom getter:

```typescript
get fullName(): string {
    return this.firstName + ' ' + this.lastName;
}
```

But, if I try to use this property as `optionTextField`, then the I see the only empty string, without any error.

**Comment by optimistex** [comment]
Hi!
Are you use such code?
```html
<ngx-select [optionTextField]="fullName">
```
Pay attention on the square brackets.

**Comment by optimistex** [comment]
If the trouble is not solved then show me your template and code, please.

**Comment by ZhukV** [comment]
No, is not working, because the angular try to bind the value to the property.

Maybe problem exist in TypeScript, because the method `hasOwnProperty` returns false for custom getter/setter.

**Comment by optimistex** [comment]
# Fixed

The `hasOwnProperty` was changed to `'propertyName' in object`.
Borrowed there: https://stackoverflow.com/a/11040508/6300699

```typescript
class SmartObject {
    constructor(public id: number, public firstName: string, public lastName: string) {
    }

    get fullName(): string {
        return '+' + this.firstName + ' ' + this.lastName + '+';
    }
}

@Component({
    selector: 'single-demo',
    template: `
        <ngx-select [items]="items" optionTextField="fullName"></ngx-select>`,
})
export class SingleDemoComponent {
    items = [
        new SmartObject(1, 'firstName 1', 'lastName 1'),
        new SmartObject(2, 'firstName 2', 'lastName 2'),
        {id: 3, firstName: 'firstName 3', lastName: 'lastName 3', fullName: '+++ 3'},
        {id: 4, firstName: 'firstName 4', lastName: 'lastName 4', noName: '+++ 3'},
        // ...................
    ];

    constructor() {
        const t = new SmartObject(1, 'firstName 1', 'lastName 1');
        console.log('t', t);
        console.log('t.fullName', t.fullName);

        console.log(`t.hasOwnProperty('firstName')`, t.hasOwnProperty('firstName'));
        console.log(`t.hasOwnProperty('fullName')`, t.hasOwnProperty('fullName'));
        console.log(`t.hasOwnProperty('noName')`, t.hasOwnProperty('noName'));

        console.log(`'firstName' in t`, 'firstName' in t);
        console.log(`'fullName' in t`, 'fullName' in t);
        console.log(`'noName' in t`, 'noName' in t);
    }
}
```
![image](https://user-images.githubusercontent.com/11228640/36065489-d931448e-0eac-11e8-9e2b-bc79bec6a4af.png)
![image](https://user-images.githubusercontent.com/11228640/36065505-eae1dd38-0eac-11e8-8f57-73be42d9d540.png)

**Comment by optimistex** [comment]
Please upgrade to v3.3.10: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.10

**Comment by ZhukV** [comment]
Wow, very thank you for fast fixing!
