### ISSUE TITLE
Delete key clears the selected item even if [allowClear]="false"

### ISSUE THREAD

**Issue by amiram** [optimistex/ngx-select-ex#191]
**Describe the bug**
Even when `[allowClear]="false"` you can still delete the selected item by moving the focus to the select and press delete.

**To Reproduce**
https://stackblitz.com/edit/ngx-select-ex-scratch-ceu8mf
1. Select an item.
2. Move the focus to another input.
3. Move the focus to the select with Tab key.
4. Press Delete key. Item is cleared.

**Expected behavior**
Item shouldn't be cleared since `[allowClear]="false"`

**Comment by optimistex** [comment]
Closed by https://github.com/optimistex/ngx-select-ex/pull/192
