### ISSUE TITLE
Implement custom template for an option

### ISSUE THREAD

**Issue by ZhukV** [optimistex/ngx-select-ex#20]
Hi. In many cases, the developer wants the generate custom text for the option of select.

As an example:

I have the model - `User`. This model has next properties - username, firstName, and lastName. By logic, I want to concatenate these parameters for the option with next logic:

```html
<span class="full-name">{{ firstName }} {{ lastName }}</span><span class="text-mutted">({{ username }})</span>
```

Now, we should create the property with this code dynamically or create the custom getter. Maybe better will create the functionality for generating custom codes?

```html
<ngx-select
  [items]="users"
  [disabled]="processing"
  [(ngModel)]="selectedUser"
  optionTextField="generateSelectionOption($event.user)"
  optionValueField="id"
></ngx-select>
```

```typescript
void generateSelectOption(user: UserResource): string {
    return 'abra-cadabra'; // Generate code here
}
```

**Comment by optimistex** [comment]
Hi!
Right now for reach the goal, you are may transform items like there: https://github.com/optimistex/ngx-select-ex/issues/16#issuecomment-364255833

Currently, I have an idea to implement templates. After implementation, your goal will be reached with the code:
```html
<ngx-select
  [items]="users"
  [disabled]="processing"
  [(ngModel)]="selectedUser"
  optionValueField="id"
>
            <ng-template ngx-option-tmp let-item="item">
                <span class="full-name">{{ item.firstName }} {{ lastName }}</span>
                <span class="text-mutted">({{ item.username }})</span> 
            </ng-template>
</ngx-select>
```

What do you think about the idea?

**Comment by ZhukV** [comment]
Very nice idea. But, I think what the usage simple ng-content with custom selector maybe easier.

```html
<ngx-select
  [items]="users"
  [disabled]="processing"
  [(ngModel)]="selectedUser"
  optionValueField="id"
>
            <ngx-select-item>
                <span class="full-name">{{ item.firstName }} {{ lastName }}</span>
                <span class="text-mutted">({{ item.username }})</span> 
            </ngx-select>
</ngx-select>
```

And this solution has next improvements:

* We can use custom attribute in `ngx-select-item`
* Easy for understanding.

**Comment by optimistex** [comment]
I will consider sub templates in angular and I will implement your version if it is possible.

**Comment by optimistex** [comment]
It's done: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.11
Check the documentation: https://github.com/optimistex/ngx-select-ex#templates

___________
@ZhukV 
> I think what the usage simple ng-content with custom selector maybe easier.

I have not found any way for that. I can ensure access to the variables only inside the `ng-template` with the prefix `let-`.

**Comment by ZhukV** [comment]
Wow, very thank you for fast implementation!!!
