### ISSUE TITLE
Can't resolve 'lodash.isequal' after updating angular to v13.3.0

### ISSUE THREAD

**Issue by Muhammad-VII** [optimistex/ngx-select-ex#202]
**Describe the bug**
Can't resolve 'lodash.isequal' after updating angular to v13.3.0
this message appers to me on application serve after i updated to v13.3.0

**Comment by Muhammad-VII** [comment]
I ran npm i --force and it fixed it 🤷🏼

**Comment by optimistex** [comment]
@Muhammad-VII try **v8.0.1** https://github.com/optimistex/ngx-select-ex/releases/tag/v8.0.1

> add lodash.isequal to peerDependencies ([fbe2f6b](https://github.com/optimistex/ngx-select-ex/commit/fbe2f6b6e70e850f6ec751628667be42419c46c2))

Does it solve the issue?

**Comment by Muhammad-VII** [comment]
> @Muhammad-VII try **v8.0.1** https://github.com/optimistex/ngx-select-ex/releases/tag/v8.0.1
> 
> > add lodash.isequal to peerDependencies ([fbe2f6b](https://github.com/optimistex/ngx-select-ex/commit/fbe2f6b6e70e850f6ec751628667be42419c46c2))
> 
> Does it solve the issue?
> 

It's already fixed after running npm i 🤷🏻

**Comment by ptbjocom** [comment]
Problem solved after installing: "lodash.isequal": "^4.5.0"

npm i --save lodash.isequal
