### ISSUE TITLE
Support the functionality to add dynamic options

### ISSUE THREAD

**Issue by newdevsoft7** [optimistex/ngx-select-ex#21]
I can't add not existed option, does this package support the dynamic option population?

**Comment by optimistex** [comment]
Just change the items property and it is must to be enough.

**Comment by newdevsoft7** [comment]
how can I change the items property?

**Comment by optimistex** [comment]
```typescript
import {Component} from '@angular/core';

@Component({
    selector: 'single-demo',
    template: `<ngx-select [items]="items"></ngx-select>`
})
export class SingleDemoComponent {
    public items: string[] = [];
    private counter = 1;

    constructor() {
        setTimeout(() => {
            setInterval(() => {
                this.items.push('item ' + this.counter++);
            }, 2000);
        }, 2000);
    }
}
```
Just click on the select and watch:
![image](https://user-images.githubusercontent.com/11228640/36101848-8f1e43f4-101b-11e8-8e7c-9c7f570cf92e.png)

After few secontds:
![image](https://user-images.githubusercontent.com/11228640/36101867-9885e01e-101b-11e8-87b9-6b1f88725be3.png)

**Comment by newdevsoft7** [comment]
Nice. but when I can't find the option, how can I hook this?

**Comment by optimistex** [comment]
Are you talking about a something event firing on a search text is typed and the rendered item list is empty?

**Comment by newdevsoft7** [comment]
Yep

**Comment by optimistex** [comment]
I think that I can add the event `(filtered)` with returning items for rendering.

**Comment by newdevsoft7** [comment]
Thank you very much. I should use this plugin. Excuse me, but can you make a plunkr for this?

**Comment by newdevsoft7** [comment]
By the way, when I use this plugin with Angular Material, how should I do for?

**Comment by optimistex** [comment]
Yes. Sure. Make a plankr. I will help me to understand your case.

**Comment by optimistex** [comment]
> By the way, when I use this plugin with Angular Material, how should I do for?

Currently, I have no experience with Angular Material and I am not sure about it is working correctly.
But, If you are want to collaborate. Then I think that we can ensure support for the angular material.
If it is interesting for you then text me to the Telegram: [@optimistex](https://t.me/optimistex)

**Comment by newdevsoft7** [comment]
@optimistex I am sorry, but I am not familiar with Angular Material, and I am in a busy condition with my client's work. so I am afraid that I can't help you now.

**Comment by optimistex** [comment]
Okay. Do not worry.
Return to the topic.
Show your case. And I will try to think up an optimal solution with the `ngx-select-ex`.

**Comment by newdevsoft7** [comment]
I would like to use children-based select with a dynamic option population.
e.g. if I can't find an option when I type, I should fetch data from backend with the entered text. And then I should populate the entered text as an item and the fetched data as other items.
That's my story. you should use children demo. 
![image](https://user-images.githubusercontent.com/33376415/36103897-4aba26ce-105c-11e8-8c67-22e004900d30.png)

**Comment by optimistex** [comment]
I have the similar case in my the general project.
Your described case has a trouble.

# Look at  the trouble:
- on the backend exists 1000 record of data.
- I suppose that you are loading just a part of records, 100 for example.
- suppose you are written some text, `ho` for example.
- the select was filtered and found 3 records. 
But! We forget about the rest 900 records on the backend. It was not filtered... However, on the backend may be multiple records satisfying the search text `ho`. And by your logic, a user will not see the records from the backend.

# Solution!
We have to send a search request for all typed text, but with debounce(!).

For clarity look at the real code from my project:
```html
<ngx-select class="ls-select" id="position-name" [formControl]="searchPosControl"
            [items]="subjSearchPosItems | async" optionValueField="uuid" optionTextField="name"
            (typed)="searchPosTyped.next($event)"
            placeholder="Поиск позиции"
            [allowClear]="true">
</ngx-select>
```
```typescript
export class PageOrderEditComponent {
   // ...........
    public searchPosTyped = new Subject<string>();
    public searchPosControl = new FormControl();
    public subjSearchPosItems: Observable<INomenclaturePosition[]>;
   // ...........
    private initBehaviorsOfAddPosition() {  // called from the constructor
        // for live search in searchPosControl
        this.subjSearchPosItems = this.searchPosTyped
            .debounceTime(500)
            .flatMap((text: string) => this.catalog.getNomenclaturePositionList({search: text}))
            .flatMap((itemList: ICrudList<INomenclaturePosition>) => Observable.from(itemList.items)
                .map((item: INomenclaturePosition) => Object.assign({name: item.values.f_name}, item))
                .toArray()
            )
            .share(); 
      // .............
   }
}
```

**Comment by newdevsoft7** [comment]
Awesome!

**Comment by newdevsoft7** [comment]
Thank you very much!

**Comment by TFeld00** [comment]
@optimistex Using the solution from your comment only loads 100 results, would it be possible to load more when scrolling to the bottom of the dropdown (as in select2)?
Eg. an event could be fired that loads more results.

**Comment by optimistex** [comment]
@TFeld00 I think it's possible. I can make an event with parameters item, index, items.
Then you will can subscribe to the event and decide when send a request for downloading more records.

What do you think about the idea?

**Comment by TFeld00** [comment]
@optimistex Sounds good :)

**Comment by optimistex** [comment]
@TFeld00 Well. I'll implement it a little later.

**Comment by TFeld00** [comment]
@optimistex No problem, I'll see if i can work around it atm

**Comment by optimistex** [comment]
It's done: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.11
Check the documentation: https://github.com/optimistex/ngx-select-ex#api     

(navigated) | Fired on navigate by the dropdown list. Returns: INgxOptionNavigated.
-- | --
