### ISSUE TITLE
Edit no result found

### ISSUE THREAD

**Issue by arthurfrancioni** [optimistex/ngx-select-ex#22]
I would like to know if I can edit the result not found with a link to add a new record.

This image shows how the

![result fw](https://user-images.githubusercontent.com/1223383/36223964-2c7df134-11ad-11e8-8554-d5a00c85970a.png)

**Comment by optimistex** [comment]
Currently, ngx-select-ex have not the feature.
But. There is exists an idea for implementing templates for items: https://github.com/optimistex/ngx-select-ex/issues/20#issuecomment-364735362

I think we need a little develop the idea and to add a template and for "Not found item". It is similar tasks...
What do you think?

**Comment by arthurfrancioni** [comment]
It's gonna be great. When are you planning to launch this feature? do you need any help? thanks!

**Comment by optimistex** [comment]
Soon. I am doing it right now...

**Comment by optimistex** [comment]
It's done: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.11
Check the documentation: https://github.com/optimistex/ngx-select-ex#templates
