### ISSUE TITLE
Feature Request: Delete Selections via Keyboard

### ISSUE THREAD

**Issue by jessemorton** [optimistex/ngx-select-ex#23]
Thanks for taking on this project, keeping it up to date. Nicely done so far! Do you have any intention of making it doable to delete selections with the backspace key?

**Comment by optimistex** [comment]
You are welcome! And I am glad that my job is useful for someone.
About the subject.
Currently, the function is implemented on the key Delete. Are tried it? Is it enough?

**Comment by optimistex** [comment]
I think that your wish is a candidate to add to `NgxSelectOptions` (currently just in a discussion):
https://github.com/optimistex/ngx-select-ex/issues/18#issuecomment-364400315

**Comment by jessemorton** [comment]
OK, I didn't think to try the Delete key. That does work and is sufficient on a technical level, though on a user-experience level I'd say that the Backspace key is more appropriate. I expect Delete to delete what comes *after* the cursor, not what comes *before*. If you were able to make it configurable like via `NgxSelectOptions` that'd be great. Thank you!

**Comment by optimistex** [comment]
Currently, the backspace maybe terrible when a user using search. Just figure that. User typed some a text and then he has press and holds the backspace key. Then firstly will be deleted the search text and then all selected items on the control.

But! Okay. I'll implement the options for customizing such behavior.

**Comment by jessemorton** [comment]
Good point! I'd accept that as a risk of holding down the Backspace key. :) Just to confirm I'm not alone, just checked for example with the https://selectize.github.io/selectize.js/ library and what you described is what can happen. But it's more natural than needing to learn Delete.

**Comment by optimistex** [comment]
I accept. More easy add some feature instead of retraining users. It has the right to live.

**Comment by optimistex** [comment]
After a next release, you will be able to change the key code to delete selected items.
Sample code for solving this issue:
```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import { NgxSelectModule } from 'ngx-select-ex';

@NgModule({
  imports: [BrowserModule, NgxSelectModule.forRoot({keyCodeToRemoveSelected: 8})],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```
Please wait the release!

**Comment by optimistex** [comment]
Solved! Check the release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.0
