### ISSUE TITLE
Erroneous type="button"?

### ISSUE THREAD

**Issue by jessemorton** [optimistex/ngx-select-ex#24]
When using the `multiple` mode, I noticed that the rendering isn't very good on Mac Chrome, like a native button with white text. In the HTML, I see why: `type="button"` is located on the `<span>` that has a class of `ngx-select__selected-plural`. That `type="button"` causes Chrome to set `-webkit-appearance: button` in the CSS which just looks bad. I'm able to override the style to `-webkit-appearance: none` but thought you may want to change the `type` attribute to `role` instead.

![test](https://user-images.githubusercontent.com/914094/36291579-66df3c4a-1291-11e8-9606-60c3aec4e0d2.png)

**Comment by optimistex** [comment]
Thanks for the report.
Sadly I have not an ability to test that on the MacOS.

Please, help me with it!
1. Way:
   * Try to change the HTML in the browser console for reach the better result.
   * Give me received HTML-code, and maybe CSS.
   * I will change the package.
2. Way:
   * Update the code by yourself and make a pull request.
   * Check the contribute: https://github.com/optimistex/ngx-select-ex#contribute

**Comment by jessemorton** [comment]
OK, let's go with Way 1 this time, since it's pretty simple. I think you could just remove the `type=button` attribute from `span.ng-select__selected-plural`. Doing so via console doesn't seem to have negative side effects for me, and makes the appearance more as expected.

![test-name](https://user-images.githubusercontent.com/914094/36312077-e02e555c-12f2-11e8-8606-f87498fdf3cb.png)

**Comment by optimistex** [comment]
Solved! Check the release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.0
