### ISSUE TITLE
async seems not update

### ISSUE THREAD

**Issue by tracychubb** [optimistex/ngx-select-ex#25]
Hi,

`this.customerNames = this.customerService.customer$ // from services with BehaviorSubject`

This normal dropdownlist works
```
<select class="form-control" formControlName="customerId" (change)="customerSelected()">
    <option *ngFor="let c of customerNames | async" value="{{ c.id }}">{{ c.firstName +' '+ c.lastName }}</option>
</select>
```

This async not update : )
```
<ngx-select 
    formControlName="customerId"
    [allowClear]=true
    [items]="customerNames | async"
    optionTextField="firstName"
    (select)="selected($event)"
    (remove)="removed($event)"
    placeholder="Select Customer">
</ngx-select>
```
Do i miss something ? : )

Thanks

**Comment by optimistex** [comment]
Hi!
I was not thinking of this case. That is interesting.

Right now you're can do this:
```typescript
this.customerNames.subscribe( items => customerNameList);
```
```html
<ngx-select [items]="customerNameList" ... ></ngx-select>
```
________
I will make support with the async pipe a little later.

**Comment by tracychubb** [comment]
`this.customerNames.subscribe( items => customerNameList);` seem still not updating : )

in .ts i changed to this (worked with normal dropdownlist)
```
this.customerService.customer$.subscribe((items) => {
    this.customerNames = items;
})

```


in .service
```
customerSubject = new BehaviorSubject<Customer[]>([]);
customer$ = this.customerSubject.asObservable();

```

It's ok i will wait the the async pipe version

Thanks optimistex : )

**Comment by rogercoder** [comment]
Yeah, I can't get async population working either ...

**Comment by perrosen** [comment]
Yeah having issues getting this to work. Looked at another issue but (https://github.com/optimistex/ngx-select-ex/issues/21) still no luck. Would be great with some expanded documentation since this is probably a quite common scenario.

**Comment by optimistex** [comment]
I have check working the async pipe right now and not found any issues. Check the little test code.

```typescript
import {Component, OnDestroy} from '@angular/core';
import {BehaviorSubject} from 'rxjs/BehaviorSubject';

@Component({
    selector: 'single-demo',
    template: `<ngx-select [items]="subjItems | async"></ngx-select>`
})
export class SingleDemoComponent implements OnDestroy {
    public subjItems = new BehaviorSubject([]);
    private _ngxDefaultInterval;

    constructor() {
        const items = [];
        let itemNum = 1;
        this._ngxDefaultInterval = setInterval(() => {
            items.push('item ' + itemNum++);
            this.subjItems.next([].concat(items));
        }, 2000);
    }

    ngOnDestroy(): void {
        clearInterval(this._ngxDefaultInterval);
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/11228640/37008442-06fe5d4a-20f3-11e8-8eb5-e227c860d715.png)

And after several seconds:
![image](https://user-images.githubusercontent.com/11228640/37008475-38a5687a-20f3-11e8-91ad-9ac491136df2.png)

**Comment by optimistex** [comment]
Somebody give me code-sample for replay the issue.

**Comment by rikimm** [comment]
I reopen this case

I use my code in this way:

`
country: Observable<any>;

this.country = this.userService.getLang(this.account);

Html
<ngx-select [items]="country|async"  formControlName="id_lang"></ngx-select>
`

as I put it, it doesn't work

Regards.
