### ISSUE TITLE
How to use `form-control-lg` class?

### ISSUE THREAD

**Issue by altbdoor** [optimistex/ngx-select-ex#27]
Like the title says, Bootstrap has a `form-control-lg` / `input-lg` class to make the element bigger in size. How would I use this class with this library? Thanks.

Bootstrap v3 documentation: https://getbootstrap.com/docs/3.3/css/#forms-control-sizes
Bootstrap v4 documentation: https://getbootstrap.com/docs/4.0/components/forms/#sizing

**Comment by optimistex** [comment]
Accepted as a request for enhancement.
I think to the option `size` to the component. And you will be able to change a size of the component.

**Comment by optimistex** [comment]
Solved! Check the release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.0
