### ISSUE TITLE
backwards compatible with Angular 2 ?

### ISSUE THREAD

**Issue by tc987** [optimistex/ngx-select-ex#28]
tried to install in my project and seems fine `npm i ngx-select-ex@ng4 --save,` does it support Angular 2 officially?

**Comment by optimistex** [comment]
I do not test it on Angular 2. But Angular 2 is similar to Angular 4. 
We faced critical changes on the Angular 5.

My recommendation to you is to upgrade your application so soon as you are can. I think in the future we can face more changes and upgrading will be more hardest.
