### ISSUE TITLE
When the dropdown item is too long, the textbox breaks

### ISSUE THREAD

**Issue by optimistex** [optimistex/ngx-select-ex#29]
The original issue: https://github.com/valor-software/ng2-select/issues/943

**Comment by s4354035** [comment]
Adding some styling can fix the issue, it may not be the best but it can work... 

.ngx-select__placeholder {
    width: calc(100% - 8px);
    overflow: hidden;
    text-overflow: ellipsis;
}
.ngx-select__selected-single {
    width: calc(100% - 31px);
}
.ngx-select__selected-single > span, .ngx-select__item > span {
    width: 100% !important;
    overflow: hidden;
    text-overflow: ellipsis;
}

**Comment by optimistex** [comment]
Solved! Check the release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.0
