### ISSUE TITLE
How to delete search text on item selection ?

### ISSUE THREAD

**Issue by BBellenoue** [optimistex/ngx-select-ex#30]
Hi,

First of all thanks for the great work. My last one this time ;)
Is is possible to delete the search text when an item has been selected ?

![prtscr capture](https://user-images.githubusercontent.com/24569090/36730342-6515a1f8-1bc7-11e8-81c5-dc0275de353d.jpg)

**Comment by optimistex** [comment]
@BBellenoue Good question.
I think that need to add some option like an `autoClearSearch` for the multiple's mode.

**Comment by BBellenoue** [comment]
That would be nice.

**Comment by BBellenoue** [comment]
FYI this is already how it works in the original ng2-select.

**Comment by optimistex** [comment]
> FYI this is already how it works in the original ng2-select.

Yes. You are right. But I decided that better to save a search text. 
Just imagine a case where a user has to select a few items by one a search text. I think he will be angry to retyping the same text after each selected item.

**Comment by optimistex** [comment]
Solved! Check the release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.0
