### ISSUE TITLE
Possible to select whole object instead of just returning id value?

### ISSUE THREAD

**Issue by tc987** [optimistex/ngx-select-ex#31]
Just a suggestion. Currently it returns the value of the selected item only, is it possible to also return the id just like in the ng2-select? Probably will be useful. Thanks.

**Comment by optimistex** [comment]
My main idea that the event (select) works like a mirror of the [(ngModel)] or [formControl].
Somebody needs the feature yet? Please vote here to let me know that the feature is needed. What the cases for it?

**Comment by perrosen** [comment]
I guess one could argue there should be on option as [ngValue] in native selects. Instead of just limiting only selecting an ID we could be able to select the whole object. This could be useful if since you then can skip the step of looking up the ID in a collection and then getting the values you need.

**Comment by jackiewang5566** [comment]
Is there an API to select the whole object instead of just selecting ID? 
I didn't find it in documentation. It seems that I can only select the id value of the selected object.

**Comment by optimistex** [comment]
@jackiewang5566 No. Currently, it's impossible.
But. You can make a different issue and maybe I will implement it.  It's depend from my free time.

**Comment by optimistex** [comment]
I think about adding some option for switch return value/object.
Once I will implement it when I will get a little free time.

**Comment by optimistex** [comment]
**It's done!**

Released in development branch: https://github.com/optimistex/ngx-select-ex/releases/tag/3.5.3
To install use: `npm i ngx-select-ex@dev`

Try the example: https://stackblitz.com/edit/ngx-select-ex-issues-31?file=app/app.component.ts
________________
Thanks to all who let me know that the feature is useful. It motivates me do it faster ))

**Comment by optimistex** [comment]
It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.5.4

**Comment by jackiewang5566** [comment]
3.5.4 is for ng5 right? Is this new feature included in ng4 version?

**Comment by wilker7ribeiro** [comment]
I don't think that the issue was solved, it's more like a workaround.

I was planning to migrate from another select component, but the real formControl value is the id property still.
Ex: I cant use the whole object in Validators.
