### ISSUE TITLE
change selected field to input field

### ISSUE THREAD

**Issue by VoroshilovMax** [optimistex/ngx-select-ex#32]
Hi everybody!
How to change the input field. I need a search instead of a choice. As well as in multiplayer mode, I need in single mode. And is there an autofocus function?
Thanks for the support :)

**Comment by optimistex** [comment]
Hi!

> And is there an autofocus function?

No. But you are can set focus form yourself by @ViewChild
______
> How to change the input field. I need a search instead of a choice. As well as in multiplayer mode, I need in single mode.

Please, explain your idea in details and maybe with some pictures.

**Comment by VoroshilovMax** [comment]
On my website I have this form.
![1](https://user-images.githubusercontent.com/31731894/36977582-3ffdddbc-20b4-11e8-9990-f8c32eb357ec.jpg)
First I need to click on the input field. After that appears the pop-up menu . And only then I can enter something.
![two](https://user-images.githubusercontent.com/31731894/36977632-696cb5d8-20b4-11e8-8f81-825fb6d9d367.jpg)
But I want to immediately enter text, without clicking on the input field. As shown in the photo below
![3](https://user-images.githubusercontent.com/31731894/36977731-beb0fb26-20b4-11e8-8f23-abdd042bd418.jpg)
![4](https://user-images.githubusercontent.com/31731894/36977737-c1e75466-20b4-11e8-9f90-4c0cd90736fe.jpg)
Just like in a multiplane, but with only one choice.

**Comment by optimistex** [comment]
@VoroshilovMax Thank you for the explanation.
As I understand, you want some functional for custom control of the open/close menu? Is it enough?
I mean you could get an instance via `@ViewChild` and use methods `optionsOpen()` and `optionsClose()`. Currently, the methods is in private, but if it will enough for you, then I might set them as public methods.

**Comment by optimistex** [comment]
Methods `optionsOpen()` and `optionsClose()` declared as public.
For install use: `npm i ngx-select-ex@dev`

**Comment by optimistex** [comment]
It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.3

**Comment by abelardolg** [comment]
Hi again,
I made these changes: 

mytest.component.html: 
+ Added '#selOperadora'

mytest.component.ts:
+ Declared   
`@ViewChild('selOperadora') selectOperadoras: ElementRef;`
+ ngAfterViewInit method: 
`this.selectOperadoras.nativeElement.optionsOpen();`

...but it doesn't work.
What's wrong?

I updated my github repo in order to reflect these changes.
Best regards.

**Comment by optimistex** [comment]
Check the pull request. Your code hade some errors that I fixed.

**Comment by abelardolg** [comment]
Thanks for your help, @optimistex  👍
