### ISSUE TITLE
`keyCodeToRemoveSelected` uses deprecated methodology for key references

### ISSUE THREAD

**Issue by jessemorton** [optimistex/ngx-select-ex#33]
Really appreciate your work on the `keyCodeToRemoveSelected` feature, but I recall now that the numeric way of referring to keys is deprecated. See this relevant SO answer that links to Mozilla's docs on the issue: https://stackoverflow.com/a/43418287/4185989 May want to update how this is configured in ngx-select-ex when you have a chance.

**Comment by optimistex** [comment]
Tanks a lot. It seems has no effect on public part. I will fix it a little later in a next release.

**Comment by optimistex** [comment]
@jessemorton It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.5.0
