### ISSUE TITLE
Initialize with a value

### ISSUE THREAD

**Issue by bm-software** [optimistex/ngx-select-ex#36]
Hi,
I'm developing a gym managing application and obviously I have screens for subscriptions creation and edit. While in edit mode I would like to initialize the select value with the current object value but I'm not able to do that.

Here is my code:

    <ngx-select id="subscriptionType" name="subscriptionType"
                            [allowClear]="true"
                            [items]="subscriptionTypeOptions"
                            [(ngModel)]="model.subscriptionTypeId"
                            (select)="setSubscriptionType($event)"
                            (remove)="subscriptionTypeRemoved($event)"
                            placeholder="Seleziona..."
                            formControlName="subscriptionType">
                </ngx-select>

I'm populating the `model` object inside ngOnInit method and I'm making a call to patchValue too to initialize the form status but the component shows always the placeholder,

How can I solve that?

**Comment by optimistex** [comment]
Check the troubles:
1. Do not mix the `ngModel` with the `formControl` in the one component instance. It may bring any unwanted behavior.
2. I see that you use the select and the remove events. Better to use the `formControl`. I wrote about it in the README:

         Warning! Although the component contains the select and the remove events, 
         the better solution is using valueChanges of the FormControl.

I had prepared an example for you: https://stackblitz.com/edit/ngx-select-ex-issues-36

**Comment by bm-software** [comment]
Thank you very much! Before you library I was using `ng2-select` and it needs that:

     this.renewForm.patchValue({
                subscriptionType: [{
                    id: this.subscription.type.id,
                    text: `${this.subscription.type.name} (${this.subscriptionModePipe.transform(this.subscription.type.mode)})- ${this.subscription.type.duration} ${this.subscription.type.duration == 1 ? 'mese' : 'mesi'} - Eur. ${this.decimalPipe.transform(this.subscription.type.pricePerMonth, '1.2-2')} al mese`
                }]
            });

with your library it is sufficient to use: 

        this.renewForm.patchValue({ subscriptionType: this.subscription.type.id });

And now it works.
However I will follow your other advice too.

Thank you :)

**Comment by bm-software** [comment]
Only one more question.
I've to perform specific actions when user selects or removes the value. This is the reason why I'm using `select` and `remove` events. With `valueChanges` approach I can reach the same result checking the value: if it's null (removed) or if it's not null (selected), right?

**Comment by optimistex** [comment]
> I can reach the same result checking the value: if it's null (removed) or if it's not null (selected), right?

On the start reimplementation, I did not want to add the `select` and `remove` events. But later in one of the issues, someone asks me to add it for solving some specific task.
Currently, I do not recommend to use the events because it is the way to a headache. Use it if you have not found other way only.
