### ISSUE TITLE
How can i call any method on change dropdown value 

### ISSUE THREAD

**Issue by YogeshBorkhade** [optimistex/ngx-select-ex#37]
I am using ngx-select-ex for selecting single  value. Normally in html select we have one event "onChange". Is it available in ngx-select-ex ? Can you please help me to trigger a method onchange event

**Comment by optimistex** [comment]
What do you mean "on change drop down value"?
- Is selected value from the list?
- something other?

**Comment by YogeshBorkhade** [comment]
Select Value from List

**Comment by YogeshBorkhade** [comment]
is (select) works as same ? i wants to make sure about it that why i raise this issue

**Comment by optimistex** [comment]
> is (select) works as same ? i wants to make sure about it that why i raise this issue

Yes. But better to use is `formControl`:

```typescript
import {Component} from '@angular/core';
import {FormControl} from '@angular/forms';

@Component({
    selector: 'app-example',
    template: `<ngx-select [items]="['111', '222']" [formControl]="selectControl"></ngx-select>`
})
class ExampleComponent {
    public selectControl = new FormControl();
    
    constructor() {
        this.selectControl.valueChanges.subscribe(value => console.log(value));
    }
}
```

**Comment by optimistex** [comment]
Life example for you: https://stackblitz.com/edit/ngx-select-ex-example-formcontrol?embed=1&file=app/app.component.ts

**Comment by YogeshBorkhade** [comment]
Thank you @optimistex

**Comment by optimistex** [comment]
@shahabblouch I'm not sure that I right understood what you want. I have updated the example for you:
https://stackblitz.com/edit/ngx-select-ex-example-formcontrol?file=app/app.component.ts

Check, and have a look at the browser console.

If have you meant something else then make an example on StackBlitz to show your case and elaborate better your question.
