### ISSUE TITLE
The text filter does not work in Chrome Mobile (Android Version)

### ISSUE THREAD

**Issue by bipinkumarsingh** [optimistex/ngx-select-ex#41]
Hello,

While testing I found that the drop down is not loading mobile Chrome(Android Nougat) .
No calls are going to backend , while typing the search criteria.

I am using ngx-select-ex with Angular 4.1.3.

Please help to resolve the issue.

Regards,
Bipin

**Comment by bipinkumarsingh** [comment]
I check demo is working fine but the options are static and loaded in advance,
While in my case the options are dynamic.
I will create a sample , and will share.

**Comment by optimistex** [comment]
Please, make an example there: https://stackblitz.com

I need some example to replay the issue. Then I will can to solve it.

**Comment by tzru** [comment]
Hi,
I have the same issue.
In the mobile, the search is not working properly.
Although the search text is bolded in appropriate items, the list is not filtered by it.
It occours in the demo too.

**Comment by tzru** [comment]
The image describing the bug is attached.
![screenshot_2018-03-19-11-58-02](https://user-images.githubusercontent.com/37533830/37589397-d242ea14-2b6d-11e8-968e-75bd6f0910cc.jpg)

**Comment by optimistex** [comment]
Is it the Safari?

**Comment by tzru** [comment]
No. It's Chrome.

**Comment by optimistex** [comment]
On Android? Which version?

**Comment by optimistex** [comment]
# The bug!
OS: Android 5.0.2
Browser: Chrome
Description:
The text filter does not work. Apparently because of filtering by keyUP event. Have to change it to filter by the `(change)` event.

![image](https://user-images.githubusercontent.com/11228640/37590327-ffdd5094-2b78-11e8-8528-199061e92eaa.png)

**Comment by bipinkumarsingh** [comment]
Hello Konstantin,

Please share ,when we can expect , the issue will be resolved.

Regards,
Bipin KUMAR

**Comment by optimistex** [comment]
@bipinkumarsingh I fixed it in development version!
Install: `npm i ngx-select-ex@dev`
Please, keep in touch and let me know as it works.

**Comment by bipinkumarsingh** [comment]
Thanks @optimistex , I am testing.

**Comment by bipinkumarsingh** [comment]
Angular4 version is also fixed?
As i am using  ANgular 4.3.5.
npm i ngx-select-ex@ng4

**Comment by optimistex** [comment]
> Angular4 version is also fixed?
As i am using ANgular 4.3.5.
npm i ngx-select-ex@ng4

Noop. Ok. I'll rebuild for ng4.

**Comment by optimistex** [comment]
It's done!
**Install:** `npm i ngx-select-ex@ng4-dev`

**Comment by bipinkumarsingh** [comment]
Getting invalid error  while installing the above dependency.

**Comment by tzru** [comment]
Hi, I also get invalid in the angular 5 release.

**Comment by optimistex** [comment]
I have no errors. Show your errors.
![image](https://user-images.githubusercontent.com/11228640/37651773-62bbbeb8-2c4a-11e8-85d5-7d58ec0a1d16.png)

**Comment by tzru** [comment]
![capture](https://user-images.githubusercontent.com/37533830/37656635-4a6797a4-2c51-11e8-80d9-c3c9286d1943.PNG)
My  @angular/common and @angular/core version is 5.0.0. Is it a problem ?

**Comment by optimistex** [comment]
Installing to a project with the Angular5:
![image](https://user-images.githubusercontent.com/11228640/37659099-1a02ecbc-2c60-11e8-9ffd-e1ea855ef695.png)

And my `package.json` after install:
```json
{
  "name": "Lisa10",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -op runtime",
    "build": "ng build --prod && git add -A",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "@ngx-loading-bar/http-client": "^1.0.0-rc.3",
    "@types/file-saver": "^1.3.0",
    "@types/lodash": "^4.14.91",
    "angular-tree-component": "^7.0.1",
    "angular2-text-mask": "^8.0.3",
    "babylonjs": "^3.1.1",
    "canvas2svg": "^1.0.16",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "git-auto-deploy-ex": "^1.3.7",
    "intl": "^1.2.5",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "mydatepicker": "^2.4.0",
    "ng2-cache-service": "^1.1.1",
    "ng2-dnd": "^5.0.2",
    "ng2-file-upload": "^1.2.1",
    "ng2-toastr": "^4.1.2",
    "ngx-perfect-scrollbar": "^5.2.0",
    "ngx-popover": "0.0.16",
    "ngx-select-ex": "^3.4.2-dev",
    "normalize.css": "^6.0.0",
    "object-hash": "^1.1.8",
    "rxjs": "^5.5.6",
    "ts-helpers": "^1.1.2",
    "uuid": "^3.1.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.8",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by optimistex** [comment]
@tzru give me your `package.json`
I'll perform `npm install` and try to figure out what is wrong.

**Comment by tzru** [comment]
Hi,
My package.json is:

{
  "name": "open-spaces",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ngui/auto-complete": "^0.14.4",
    "bootstrap": "~3.3.7",
    "bootstrap-rtl": "~3.3.4",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.3.0",
    "ng2-select": "^1.2.0",
    "ngx-select-ex": "^3.4.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

**Comment by optimistex** [comment]
@tzru I performed the `npm i` and have no receive a problem.
Maybe source of the issue is an old version of your `NodeJs`!?

My `NodeJs` info:
```console
optimistex@main-ubuntu:/www/tmp/test$ nodejs -v
v9.9.0
optimistex@main-ubuntu:/www/tmp/test$ npm -v
5.7.1
optimistex@main-ubuntu:/www/tmp/test$ ^C
```

The install:
```console
optimistex@main-ubuntu:/www/tmp/test$ npm i

> node-sass@4.8.3 install /data/www/tmp/test/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/optimistex/.npm/node-sass/4.8.3/linux-x64-59_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /data/www/tmp/test/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.8.3 postinstall /data/www/tmp/test/node_modules/node-sass
> node scripts/build.js

Binary found at /data/www/tmp/test/node_modules/node-sass/vendor/linux-x64-59/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1380 packages from 1211 contributors in 53.757s
optimistex@main-ubuntu:/www/tmp/test$ 
```

**Comment by optimistex** [comment]
It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.3

@tzru text me if your issue still actual.

**Comment by abhinavxeon** [comment]
same issue i am facing in ngx-select-serach
