### ISSUE TITLE
Placeholder text isn't muted for single selects

### ISSUE THREAD

**Issue by Jrubzjeknf** [optimistex/ngx-select-ex#48]
As can be seen on the [demo](https://optimistex.github.io/ngx-select-ex/), the multi-select variant has muted placeholder text, however the single select variant doesn't.

The issue is that the color from the text-muted class is overridden by the `color: inherit !important;`, which is caused by [this line of code](https://github.com/optimistex/ngx-select-ex/blob/c594c42de3992a57204f208dc7cb8051a8232ec5/src/app/lib/ngx-select/ngx-select.component.scss#L66).

Workaround if anyone needs it:
```
span.ngx-select__placeholder.text-muted {
    color: <your-muted-color> !important;
}
```

**Comment by optimistex** [comment]
It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.3
