### ISSUE TITLE
Allow filtering by multiple fields

### ISSUE THREAD

**Issue by abelardolg** [optimistex/ngx-select-ex#49]
Hi,
I am a list of objects whose fields are: id, ds and selected.
I would like to search by 'id' AND by 'ds' fields, is this possible?
Thanks in advance.

**Comment by optimistex** [comment]
Hi!
Now it is possible with the [today release](https://github.com/optimistex/ngx-select-ex/releases/tag/3.4.3).
Use the callback:
```typescript
searchCallback: (search: string, item: INgxSelectOption) => boolean;
```
Example:
```typescript
searchCallback = (search: string, item: INgxSelectOption) => item.data.id === search;
```
```html
<ngx-select [searchCallback]="searchCallback" ... ></ngx-select>
```

**Comment by abelardolg** [comment]
Thanks, @optimistex 👍 
I understand that: 

- 'search'  is the term to search; 
- 'item' is the returned item after the search; 

If I have a collection of this object: {id: string, ds: string, selected: boolean}, then I could search by 'id' or by 'ds' , right? Do I understand well this new feature?  If so, then in my case it would be:

- searchCallback = (search: string, item: INgxSelectOption) => (item.id === search) ¦¦  (item.ds === search);

Finally, where should I write this piece of code? I am not sure but I think I could write an event such as "keyEvent" (@HostListener) which detects the 'Enter' key to confirm the inputted term and initiate the searching for this term, isn't it?

Let me know if I am wrong. :) 👍 
Best regards.

**Comment by optimistex** [comment]
@abelardolg Little wrong.
Explanation about `(search: string, item: INgxSelectOption) => ` 
* `search: string` - typed text from a user
* `item: INgxSelectOption` - is a wrapper around your original object. For access to the original object using the `INgxSelectOption.data`.

In the function, you have to decide show or hide the item. And return the relevant true or false result.

Example:
```typescript

export class CoolComponent {
   public searchCallback = (search: string, item: INgxSelectOption) => (item.data.id === search) || (item.data.ds === search);
}
```
