### ISSUE TITLE
To do support with Bootstrap 4

### ISSUE THREAD

**Issue by optimistex** [optimistex/ngx-select-ex#5]
- [x] implement support with "Bootstrap 4"
- [x] ensure support with "Bootstrap 3" for backward compatibilty
- [x] update readme

### with bootstrap 3
```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
```
![image](https://user-images.githubusercontent.com/11228640/35737900-2f29357e-083e-11e8-9033-0afcc33df59e.png)
![image](https://user-images.githubusercontent.com/11228640/35737786-c79034c6-083d-11e8-8011-de0bab88399e.png)

### with bootstrap 4
```html
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
```
![image](https://user-images.githubusercontent.com/11228640/35737829-f3825ffa-083d-11e8-92fb-092da424e21c.png)
![image](https://user-images.githubusercontent.com/11228640/35737845-fe09c8e6-083d-11e8-831c-e47e452b7207.png)

**Comment by optimistex** [comment]
There is detailed information about the release: https://github.com/optimistex/ng2-select-ex/releases/tag/3.3.0-rc1

**Comment by yakimko** [comment]
Thanks a lot!

**Comment by yakimko** [comment]
Thank you for your job. 
I just wanted to add one more fix.
Could you please remove this ugly background when a mouse over the select? Like here 
![ex](https://user-images.githubusercontent.com/3535655/35857595-4a13a1b0-0b42-11e8-9b36-52547a527082.gif)

**Comment by optimistex** [comment]
![image](https://user-images.githubusercontent.com/11228640/35857868-794297da-0b4b-11e8-89a3-e79606e3c86b.png)

**Comment by yakimko** [comment]
Sorry, this grey background 
<img width="399" alt="screen shot 2018-02-06 at 13 40 02" src="https://user-images.githubusercontent.com/3535655/35857971-6798b576-0b43-11e8-8a1d-3c197e1a0398.png">

**Comment by optimistex** [comment]
Understand.
Ok. I'll fix it.

**Comment by optimistex** [comment]
## Ready for next release!

### Check the preview:

![image](https://user-images.githubusercontent.com/11228640/35864766-b9acdb4c-0b63-11e8-9ac4-6d1205f9f91e.png)
![image](https://user-images.githubusercontent.com/11228640/35864771-c464f31c-0b63-11e8-99b0-03032c8433c9.png)

**Comment by optimistex** [comment]
It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.5
