### ISSUE TITLE
Supporting Keyboard Navigation

### ISSUE THREAD

**Issue by abelardolg** [optimistex/ngx-select-ex#50]
Hi,
I would like to press the down key and show the list. Obviously, when I press again the down key I would like to iterate through items.

Best regards.

**Comment by optimistex** [comment]
From the documentation:
> If you want to change the default options then use next code:

```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import { NgxSelectModule, INgxSelectOptions } from 'ngx-select-ex';

const CustomSelectOptions: INgxSelectOptions = { // Check the interface for more options
    optionValueField: 'id',
    optionTextField: 'name'
};

@NgModule({
  imports: [BrowserModule, NgxSelectModule.forRoot(CustomSelectOptions)],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```
The interfase:
https://github.com/optimistex/ngx-select-ex/blob/733f7085503657ec4da570f086de5301f5783465/src/app/lib/ngx-select/ngx-select.interfaces.ts#L27-L42

**Comment by optimistex** [comment]
Sorry. It has no option for you.
I'll add it.

**Comment by optimistex** [comment]
It's done!

You can do it with this release: https://github.com/optimistex/ngx-select-ex/releases/tag/3.5.0

The example for your case:
```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import { NgxSelectModule, INgxSelectOptions } from 'ngx-select-ex';

const CustomSelectOptions: INgxSelectOptions = { // Check the interface for more options
    keyCodeToOptionsOpen: 'ArrowDown'
};

@NgModule({
  imports: [BrowserModule, NgxSelectModule.forRoot(CustomSelectOptions)],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```

**Comment by abelardolg** [comment]
Thanks @optimistex 
Now, all I need is that the select loads my list with the collection of items: {id: string, ds: string, selected: boolean}

Best regards.

I following you!

**Comment by abelardolg** [comment]
Thanks, @optimistex 
Might you update it to the last version? I would like to check it with the supporting keyboard navigation and with the searchCallback function (to search for by an id or by a text).
Brs.

**Comment by optimistex** [comment]
Take it: https://stackblitz.com/edit/ngx-select-ex-issues-50?file=app%2Fapp.module.ts

**Comment by optimistex** [comment]
It seems like a bug of the site stackblitz.com
