### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by osajidui** [optimistex/ngx-select-ex#53]
Since https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep is deprecated. How can I customize the CSS classes for ngx-select?

**Comment by optimistex** [comment]
Hello!
Please, read the documentation:
https://github.com/optimistex/ngx-select-ex#styles-and-customization

**Comment by osajidui** [comment]
@optimistex Thanks. I went through the documentation and tried to apply CSS to `.ngx-select` class but it did not work. I can see in the DOM that it has 
```.ngx-select[_ngcontent-c2] {
}```
from which I assume that angular styling encapsulation is being applied which is why my custom css are not getting effected. Am I missing something?

**Comment by optimistex** [comment]
I got it.
You add the style into the styles of your component which contains the `<ngx-select ...>`. But you have to add the extra styles to common styles of your application.

**Comment by galvakojis** [comment]
I hope, i am not very annoying, 
but i can't figure out, how change styles `ngx-select__selected-plural `
i wanna to be able to change style of whole button, but at this moment i can change only span inside it
![image](https://user-images.githubusercontent.com/17315578/50144580-42d4ef80-02b8-11e9-9942-ef5f2fc99ed7.png)

**Comment by optimistex** [comment]
@galvakojis There are several classes:
![image](https://user-images.githubusercontent.com/11228640/50144996-2eddbd80-02b9-11e9-96d9-380d016e65b9.png)

And you can use some combinations regarding of your task.

Anyway, show your code and ask what exactly misunderstanding. I'll try to help.
