### ISSUE TITLE
Unexpecte token import.. When I am running my angular 4 application server side ..

### ISSUE THREAD

**Issue by vishalsingh123** [optimistex/ngx-select-ex#54]
dist/ngfactory/node_modules/ngx-select-ex/ngx-select-ex.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/vishalsingh/Projects/chemarc/saurabh/chemarc/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chemarc@0.0.0 start: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chemarc@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vishalsingh/.npm/_logs/2018-04-06T06_12_16_748Z-debug.log

**Comment by vishalsingh123** [comment]
@optimistex yes

**Comment by optimistex** [comment]
@vishalsingh123 I released `+ ngx-select-ex@3.5.2-ng4` from https://github.com/optimistex/ngx-select-ex/releases/tag/3.5.2

Please, check again the issue and let me know if it is actual.

**Comment by optimistex** [comment]
If it is not okay then give me your `package.json` file. I'll try to catch the bug for fix it.

**Comment by vishalsingh123** [comment]
{
  "name": “vishal”,
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "prestart": "ng build --prod && ngc",
    "start": "ts-node src/server.ts"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.3.1",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "i": "^0.3.6",
    "ng2-uploader": "^2.0.0",
    "ngx-select-ex": "^3.5.0-ng4",
    "ngx-uploader": "^3.3.11",
    "npm": "^5.8.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "babel-cli": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by vishalsingh123** [comment]
`{
  "name": “vishal”,
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "prestart": "ng build --prod && ngc",
    "start": "ts-node src/server.ts"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.3.1",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "i": "^0.3.6",
    "ng2-uploader": "^2.0.0",
    "ngx-select-ex": "^3.5.0-ng4",
    "ngx-uploader": "^3.3.11",
    "npm": "^5.8.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "babel-cli": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
`

**Comment by vishalsingh123** [comment]
its working fine with "ng serve" command
but giving error when i ran server side with "npm run start"

**Comment by optimistex** [comment]
The `package.json` is not enought.
Can you give me the whole project in a zip archive?

**Comment by optimistex** [comment]
@vishalsingh123 I can not replay the bug and do not see your activity. Closed as not an actual.
If it's still actual, please give me more info about the bug to replay it, and to reopen this issue.
