### ISSUE TITLE
By pressing the arrow at the right side of the select don't show the list of items.

### ISSUE THREAD

**Issue by abelardolg** [optimistex/ngx-select-ex#55]
Hi again,

At this site: [http://www.abelardolg.com/lab/angular/](http://www.abelardolg.com/lab/angular/) there is a select which is used to test some of its functionalities.
When I click (with the mouse) on the right arrow, the list is not showed.
You have got the code and you can take it a look to check this issue.

Brs.

**Comment by optimistex** [comment]
Please, upload your code to the GitHub: https://github.com/new
And after, give me access to the repository, or I make a fork.

**Comment by abelardolg** [comment]
Hi, 
Take a look to this repository: https://github.com/abelardolg/select-app

Since I am a newbie at Github.com, tell me if you work is well referenced.

**Comment by optimistex** [comment]
If I understand right then you clicked to the dropdown arrow (see the pictire). I tryed to replay it. But I can not to replay.
I have no idea ho to fix that I do not see. How can I replay it?
My system is: 
* Ubuntu 16.04 LTS 
* Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/11228640/38771192-56874216-4027-11e8-9920-f30a81c615dc.png)

**Comment by abelardolg** [comment]
I am downloading a fresh version of Ubuntu 16.04 LTS in order to install into VirtualBox.
I will return back to leave my comments.
See you.

**Comment by optimistex** [comment]
Since we are discussing some troubles on one example let's merge topics into one.
The discussion continues in the issue: https://github.com/optimistex/ngx-select-ex/issues/56
