### ISSUE TITLE
By tiping character by character the items are not showed

### ISSUE THREAD

**Issue by abelardolg** [optimistex/ngx-select-ex#56]
Hi,
When I type a character (ex. the 'O'  is present in several items), the items which contain it aren't showed.

Test it: http://www.abelardolg.com/lab/angular/

Brs.

**Comment by optimistex** [comment]
![image](https://user-images.githubusercontent.com/11228640/38454911-b16406f6-3a78-11e8-80e2-7101783a5168.png)
What wrong?
Do you have some items!?

**Comment by abelardolg** [comment]
When I type a character, the items which contains that character are not showed:

![image](https://user-images.githubusercontent.com/22522883/38483951-07227aa2-3bd5-11e8-8789-505c35f7687e.png)

Yes, I have some items. You will see them when you type "uno", "dos", "tres"...or "1", "2", "3"...until "10".

**Comment by optimistex** [comment]
> Yes, I have some items. You will see them when you type "uno", "dos", "tres"...or "1", "2", "3"...until "10".

Okay. I see it. And what wrong?
Everything work such as you programmed. `function (t,e){return+t===e.data.id||e.data.ds===t}` - this conditions return true only on exact match id or text. Pay attention! Exact match! Not containable!!! It is your code. If you want something more flexible then change you conditions.

For example look at the original code for compare that search text contains in the full text:
https://github.com/optimistex/ngx-select-ex/blob/d186f65c59726af34435b89745ab331f415c80e1/src/app/lib/ngx-select/ngx-select.component.ts#L434

**Comment by abelardolg** [comment]
Ok. I see it.

Since I was seeing this behaviour in your component and I wasn't any explicitly reference inside your code, I thought it was done implicitly, by default.

Thanks a lot for your patience and time. Best regards.

**Comment by optimistex** [comment]
> Since I was seeing this behaviour in your component and I wasn't any explicitly reference inside your code, I thought it was done implicitly, by default.

If you added custom filter function then it disables original compares because you said: "Don't worry! Now comparing for filtering it is my own job!".

> Thanks a lot for your patience and time. Best regards.

I glad that my job is useful for someone like you. Good luck!

**Comment by abelardolg** [comment]
I have added your suggestion:

return (!search || regExp.test(option.text)) && (!this.multiple || selectedOptions.indexOf(option) === -1); 

to the filtering but modified to my intentions:

public searchCallback = (search: string, item: INgxSelectOption) =>
    ( !search ||
      new RegExp('[a-zA-Z0-9]').test(search) ||
      (+search === item.data.id) ||
      (item.data.ds === search)
    );

After this modification:
+ I press the Arrow down key and the list appears.
+ When I type a character, this is highlighted in those items which contain this character. When I type "diez", this item is not automatically showed but it is selected.
- When I type a number, the associated item isn't selected (i. e., if I type "10", the item "diez" is not selected).

I wonder why the filtering is not working properly.

**Comment by optimistex** [comment]
I forked your repo.
It has no some specific html:
![image](https://user-images.githubusercontent.com/11228640/38770155-f6337dc2-4016-11e8-9f83-f22f567f5938.png)

Please, fix it. 

And, I make a little fix error. Check the pull requests.

**Comment by abelardolg** [comment]
Hi, 

I fixed the .html.

Sorry. 👍

**Comment by abelardolg** [comment]
I followed these steps: 
+ accepted the pullrequest
+ downloaded the code
+ npm install (to generate the node_modules dir) and this happened:

![image](https://user-images.githubusercontent.com/22522883/38794322-fe91be36-4154-11e8-9b83-d693fac63172.png)


I am still investigating these issues. 

Best regards.

**Comment by abelardolg** [comment]
This is the full log:

```
Uncaught Error: Template parse errors:
Can't bind to 'searchCallback' since it isn't a known property of 'ngx-select'.
1. If 'ngx-select' is an Angular component and it has 'searchCallback' input, then verify that it is part of this module.
2. If 'ngx-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<div class="example-block">
  <div class="example-block__item">
    <ngx-select [ERROR ->][searchCallback]="searchCallback"
                [allowClear]="true"
                [defaultValue]="): ng:///AppModule/AppComponent.html@3:16
Can't bind to 'allowClear' since it isn't a known property of 'ngx-select'.
1. If 'ngx-select' is an Angular component and it has 'allowClear' input, then verify that it is part of this module.
2. If 'ngx-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<div class="example-block__item">
    <ngx-select [searchCallback]="searchCallback"
                [ERROR ->][allowClear]="true"
                [defaultValue]="doNgxDefault()"
                [items]="items"
"): ng:///AppModule/AppComponent.html@4:16
Can't bind to 'defaultValue' since it isn't a known property of 'ngx-select'.
1. If 'ngx-select' is an Angular component and it has 'defaultValue' input, then verify that it is part of this module.
2. If 'ngx-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("  <ngx-select [searchCallback]="searchCallback"
                [allowClear]="true"
                [ERROR ->][defaultValue]="doNgxDefault()"
                [items]="items"
                placeholder="No city "): ng:///AppModule/AppComponent.html@5:16
Can't bind to 'items' since it isn't a known property of 'ngx-select'.
1. If 'ngx-select' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'ngx-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("                [allowClear]="true"
                [defaultValue]="doNgxDefault()"
                [ERROR ->][items]="items"
                placeholder="No city selected"
                (typed)="inputTyped('n"): ng:///AppModule/AppComponent.html@6:16
'ngx-select' is not a known element:
1. If 'ngx-select' is an Angular component, then verify that it is part of this module.
2. If 'ngx-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
<div class="example-block">
  <div class="example-block__item">
    [ERROR ->]<ngx-select [searchCallback]="searchCallback"
                [allowClear]="true"
                [de"): ng:///AppModule/AppComponent.html@3:4
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24668)
    at JitCompiler._parseTemplate (compiler.js:34621)
    at JitCompiler._compileTemplate (compiler.js:34596)
    at eval (compiler.js:34497)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34497)
    at eval (compiler.js:34367)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34366)
```

**Comment by abelardolg** [comment]
I modified my files in order to be completed:
+ the filtering : 
```
return (!search) ||
      (+search === item.data.id) ||
      (new RegExp('[a-zA-Z0-9]').test(search)) ||
      (item.data.ds === search);
```
returns true when I input 'diez'
but
the item 'diez' is not showed and selected (even when I type '10').

**Comment by abelardolg** [comment]
When you are so kind as to reply me...

**Comment by optimistex** [comment]
@abelardolg fixed. Check the pull request.

About your code:
The code `new RegExp('[a-zA-Z0-9]').test(search)` almost always will retorn the `true`. Look at the fix.

**Comment by abelardolg** [comment]
With that line I would like to be sure the user doesn't input any character distinct to alphabet and numbers. When I type "diez" or "10" that expression would be to return true <- it's ok.

My issue here is when I type a number (for instance, "10") the item "diez" is not showed. The same when I type the word "diez".

**Comment by abelardolg** [comment]
Yes, it was solved. :1st_place_medal: 

At the moment, I am passing parameters to the select to set its default value. When I have got it , I will return back to leave my comments.

**Comment by optimistex** [comment]
Okay. I close it. 
Reopen, or make a new issue for feature questions.

**Comment by abelardolg** [comment]
Hi again,

I would like to set as default value the value 'cuatro':
```
<app-mytest
  [valorPorDefecto]="'cuatro'"
></app-mytest>
```
Inside 'mytest.component.ts':
```
  @Input() valorPorDefecto;

 public doNgxDefault(): any {
    console.log("doNgxDefault | valorPorDefecto " + this.valorPorDefecto);
    return this.valorPorDefecto;
  }
```
Issues:
1) 'cuatro' is set as default value but it isn't selected at the select by default.
2) When I type a value and press enter, doSelect value takes the entered last  value and not the current inputted.

I updated my repo if you would like to download it and test it.

**Comment by optimistex** [comment]
Pay attention that `defaultValue` receive the VALUE. The value that defined in the option `optionValueField`.
Check the pull request.
