### ISSUE TITLE
Is it possible to use this ngx-select-ex with Angular2 v2.4.9?

### ISSUE THREAD

**Issue by AlmeerderPat** [optimistex/ngx-select-ex#58]
At the company where I work they use Angular2 v 2.4.9 and I want to use this select-box but I have an error: node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

Can I use the other version ngx-select-ex@ng4?

**Comment by optimistex** [comment]
@AlmeerderPat Yes. The ngx-select-ex@ng4 special for users with progects on angular less of 5 version

**Comment by optimistex** [comment]
I think the issue is solved.
