### ISSUE TITLE
The enter key works wrong when used immediately after filtering

### ISSUE THREAD

**Issue by b0ric** [optimistex/ngx-select-ex#60]
When a user inputs a search term and presses 'Enter' key it automatically selects the very first item though it may even be filtered out. So the only way to select an item from the keyboard is to press 'Down' + 'Enter'.

It there's a way to enable Enter key selection as it's in the [original library](https://valor-software.com/ng2-select/)?

**Comment by optimistex** [comment]
Fixed and released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.5.4
