### ISSUE TITLE
is there any way to set a value by default even when we don't have the options to show in a list?

### ISSUE THREAD

**Issue by ersurajnegi** [optimistex/ngx-select-ex#62]
I have a scenario where i need to fetch the options via ajax call in (open) event.
this is working fine, but in case of edit, not able to set the default value. as the options are not available until user opens the select box.
if i provide all the options on the page load then it's working but it's not possible to provide all the options on the page load.
i hope you understood my query.

Thanks In Advance.

**Comment by optimistex** [comment]
In the current implementation, you need to show at least one item.

**Comment by optimistex** [comment]
Looks like doest actual now...
