### ISSUE TITLE
force open close

### ISSUE THREAD

**Issue by Shemesh** [optimistex/ngx-select-ex#63]
hi,
how can i programmatic force the drop down to open or close?

**Comment by optimistex** [comment]
Hi!
Look at this: https://github.com/optimistex/ngx-select-ex/issues/39#issuecomment-373310188

Currently, have not a better solution. I will make it when I get a free time...

Closed as a duplicate. You can continue the topic: https://github.com/optimistex/ngx-select-ex/issues/39
