### ISSUE TITLE
(close) is fired but the dropdown options doesn't close

### ISSUE THREAD

**Issue by SamuelMarks** [optimistex/ngx-select-ex#66]
Tried your first cities example, and I get the `SingleDemoComponent.doClose` in my console output. But it doesn't close. How do I debug?

Angular 5.2.10; ngx-select-ex 3.5.4

EDIT: Hacked a workaround, in the `doClose()` body I ran a `.focus()` on the next form element.

**Comment by optimistex** [comment]
> EDIT: Hacked a workaround, in the doClose() body I ran a .focus() on the next form element.

Try it:
https://github.com/optimistex/ngx-select-ex/issues/39#issuecomment-373310188
