### ISSUE TITLE
It's getting slow down to open when records are more then 5k+ 

### ISSUE THREAD

**Issue by iniravjoshi** [optimistex/ngx-select-ex#73]
Hello 

In my drop down I have a around 5k+ records (in future might be more). It's Taking more time to open. I am binding with dynamic data not on initial.

Any suggestion
Thanks

**Comment by optimistex** [comment]
Tere are two ways:
1. one is lazy load a data by some filter
2. second is try the package: https://github.com/ng-select/ng-select
I saw that they solved your issue.
