### ISSUE TITLE
Selectable Group?

### ISSUE THREAD

**Issue by queejie** [optimistex/ngx-select-ex#74]
Is it possible to configure it so that a group is also selectable (not just its children)?  If not, would you be interested in adding that capability?

**Comment by optimistex** [comment]
If a group must be selectable then what different between the group and an item!?

**Comment by queejie** [comment]
The distinction is semantic.  For example, a user may wish to select Mathematics in general, or Algebra more specifically.  We set a single id for either, but the distinction is significant to the user view.

**Comment by optimistex** [comment]
Okay.
You may use the templates: https://github.com/optimistex/ngx-select-ex#templates
Just shift to the right by CSS some items with a parent option.
With this technique, you are able to make a hierarchy.
