### ISSUE TITLE
FormControl access

### ISSUE THREAD

**Issue by b0ric** [optimistex/ngx-select-ex#77]
Documentation mentions that it's possible to access **FormControl**'s _valueChanges_ event source (the end of API section). Though when I try to use it I get en error in the console:

> Can't bind to 'formControl' since it isn't a known property of 'ngx-select'.

Is this part of the documentation obsolete or it is a bug?

**Comment by b0ric** [comment]
Yes, I did.
And the component is working fine, except _valueChanges_ that I wasn't able to make to work

**Comment by optimistex** [comment]
Try the example: https://stackblitz.com/edit/ngx-select-ex-issues-45?embed=1&file=app/app.component.ts

**Comment by optimistex** [comment]
![image](https://user-images.githubusercontent.com/11228640/40650892-02f90434-633d-11e8-97ad-aa31378204d9.png)

**Comment by b0ric** [comment]
My bad,
Once I imported _ReactiveFormsModule_ as well along with _FormsModule_ it started to work.
@optimistex, thanks for the prompt response!

**Comment by optimistex** [comment]
@b0ric Glad to help you. Good luck!
