### ISSUE TITLE
AOT build fail with fullTemplateTypeCheck=true for protected methods

### ISSUE THREAD

**Issue by amiram** [optimistex/ngx-select-ex#78]
When compiling my project with fullTemplateTypeCheck=true, the build fail for usage of protected members in templates, and for another issue of wrong type.

Error is:

ERROR in node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(24,31): : Property 'sanitize' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(31,20): : Property 'optionRemove' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(47,31): : Property 'sanitize' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(51,20): : Property 'optionRemove' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(63,12): : Property 'inputKeyUp' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(64,12): : Property 'doInputText' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(67,12): : Property 'inputClick' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(84,16): : Property 'isOptionActive' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(95,31): : Property 'highlightOption' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(88,16): : Property 'optionActivate' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(88,16): : Argument of type '{ activeOption: any; filteredOptionList: TSelectOption[]; index: number; }' is not assignable to parameter of type 'INgxOptionNavigated'.
  Types of property 'filteredOptionList' are incompatible.
    Type 'TSelectOption[]' is not assignable to type 'NgxSelectOption[]'.
      Type 'TSelectOption' is not assignable to type 'NgxSelectOption'.
        Type 'NgxSelectOptGroup' is not assignable to type 'NgxSelectOption'.
          Property 'value' is missing in type 'NgxSelectOptGroup'.
node_modules/ngx-select-ex/ngx-select-ex.d.ts.NgxSelectComponent.html(93,16): : Property 'optionSelect' is protected and only accessible within class 'NgxSelectComponent' and its subclasses.

I can make a PR to fix it.

**Comment by optimistex** [comment]
> I can make a PR to fix it.
If it means the "Pull Request" then it will be nice from your side.

**Comment by optimistex** [comment]
@amiram I maked a development release with your fixes. You may install it so: 
`npm install ngx-select-ex@dev`
