### ISSUE TITLE
Multiple select doesn't work on iPad

### ISSUE THREAD

**Issue by izzmeifter** [optimistex/ngx-select-ex#82]
I've tested this on both iOS and Chrome on iPad and neither work. The first selection work fine, but none after that. Here's what happens in every case.

![img_0033](https://user-images.githubusercontent.com/4297079/41059345-80a65a7e-6989-11e8-8f2f-88a70047ebfe.PNG)

**Comment by izzmeifter** [comment]
With that said, it will work, but only if you click onto an existing chip(Object with the value) and then back into the select box. Or find another way to remove focus from the input field first.

**Comment by optimistex** [comment]
@izzmeifter Thank you for the test!
Unfortunately, I have no iOS device to test it.
Can you help me?
There is exist some unreleased fixes that look like able to solve the issue.
Just: 
1. Install development version `npm i ngx-select-ex@dev`
2. Test it on an iOS device
3. Give me a feed back

**Comment by izzmeifter** [comment]
@optimistex - I can confirm that the @dev version does indeed fix the problem :)

**Comment by optimistex** [comment]
@izzmeifter Cool! Thank you for the feedback.
Today I released the changes. So, I can switch to the general version:
`npm i ngx-select-ex@latest`
