### ISSUE TITLE
Data transform

### ISSUE THREAD

**Issue by sajidali2444** [optimistex/ngx-select-ex#84]
Hi,

Thanks nice component.
i am receiving data from api in this format [{id: 1, name:'cat1'},{id:2, name:'cat2'}]
how i can convert it to [{id: 1, text:'cat1'},{id:2, text'cat2'}] 
currently it is showing ids in option but i want to show name in option please help
can i use my custom object or same api response as items source  like this [{id: 1, name:'cat1'},{id:2, name:'cat2'}]

**Comment by optimistex** [comment]
@sajidali2444 Hi! I glad that it useful for you!

Doesn't convert it. Just use the option `optionTextField`.

The example:
```html
<ngx-select [items]="items" optionTextField="name"></ngx-select>
```
More details is there: https://github.com/optimistex/ngx-select-ex#api

**Comment by optimistex** [comment]
I think that it is not actual now.
