### ISSUE TITLE
Model reset to null when updating both items and model

### ISSUE THREAD

**Issue by Vicente69** [optimistex/ngx-select-ex#85]
Hi,

I'm working with the `ngx-select-ex` 3.5.9 component in a Angular 5 application.
With a button `click` handler, the host component triggers a update of the model bound to the component, as well as items (that completely change).

- With a regular `<select>` element, after the event handler execution, the list of items is completely refreshed in the dropdown, and the new model value is correctly bound to the corresponding new item.
- With the `<ngx-select>` element, in the event handler, I must absolutely apply the new items first, then trigger a change detection, and finally apply the new model value, to have the expected result. If I change the order of these 3 steps, or if I disable the change detection, the model remains `null`.

Here's a [Stackblitz app](https://stackblitz.com/edit/angular-qebprz) that allows to reproduce the problem.
Why a change detection must be executed with `ngx-select` in this case?
It seems it is not possible to reload at the same time both items and model value.

Can you explain me what's happening?
Thanks in advance for your help.
BR,
Vincent

**Comment by optimistex** [comment]
@Vicente69 The component shows selected item only if it in the item list. In your example, when you reloading items, the component lost selected item and it is a reason to show the null value.

Try to save selected items and include it into a new item list.

**Comment by Vicente69** [comment]
Hi @optimistex, and thank you for answer.

I understand well your answer, and the fact that the selected model is set to `null` when the items changed and no item matches the "old" selected model. I understand also the suggestion.

Let me introduce the use case: a form allows to edit a bean, and this form contains a `ngx-select` element. The user may load another bean in the form (e.g. by clicking on a link in a list aside). When the bean is loaded, the list of items is reloaded also depending on a given bean property value, and, finally, both items and bean are rebound "simulatenously". With a `<select>` element, this is working perfectly. Why wouldn't it be possible to do so with the `<ngx-select>` element?

Thanks for your clarifications :).
BR,
Vincent

**Comment by optimistex** [comment]
@Vicente69 I added a new option: keepSelectedItems
Now It exists far only in the development branch.
Try it: `npm i ngx-select-ex@dev`

And check your modified example: https://stackblitz.com/edit/ngx-select-ex-issues-85?embed=1&file=src/app/app.component.html

**Comment by helix0r** [comment]
Hi! I have seen this option in the README and wanted to use it. Then I saw, it is only available in the dev version. Have you planned to include it in the stable version? 

Thanks in advance, best regards
Tobias

**Comment by optimistex** [comment]
@helix0r It is released today!
