### ISSUE TITLE
Type ahead not getting cleared 

### ISSUE THREAD

**Issue by BTARPAR** [optimistex/ngx-select-ex#86]
Rerproduction step.
When you search for something and select the searched type ahead not getting cleared.
![typhead](https://user-images.githubusercontent.com/18237494/41366530-458550fe-6ef1-11e8-82ac-3ef5525082e5.PNG)

**Comment by optimistex** [comment]
@BTARPAR Use the option:

autoClearSearch - Auto clear a search text after select an option. Has effect for multiple = true

```html
<ngx-select [autoClearSearch]="true" ...></ngx-select>
```
