### ISSUE TITLE
placeholder out of the edges

### ISSUE THREAD

**Issue by galvakojis** [optimistex/ngx-select-ex#87]
placeholder out of the edges
![selection_567](https://user-images.githubusercontent.com/17315578/41400948-2ad9275e-6fc7-11e8-9720-2b3717834c29.png)
how to prevent this, because everything is fine with fields which been selected

**Comment by optimistex** [comment]
@galvakojis Fixed in the development branch.
Try it: `npm i ngx-select-ex@dev`

**Comment by galvakojis** [comment]
Fixed!
