### ISSUE TITLE
Add a setting: set selection by default if there is only one option

### ISSUE THREAD

**Issue by yakimko** [optimistex/ngx-select-ex#9]
https://github.com/optimistex/ngx-select-ex/issues/8 depends on this enhancement if there is only one not disabled option. 

1) test case: 
2 options: 
1 disabled
1 not disabled

If the setting is "On" select by default not disabled option

2) test case:
1 option:
Option is disabled

If the setting is "On" nothing should be selected by default

**Comment by optimistex** [comment]
It's released: https://github.com/optimistex/ngx-select-ex/releases/tag/3.3.5
