### ISSUE TITLE
Default selected items

### ISSUE THREAD

**Issue by frankbecker** [optimistex/ngx-select-ex#93]
Is there a way of setting a default selected item?
Or items for multiple options?
I did not see this in the documentation and it's a feature I'd wish this angular module had.

**Comment by optimistex** [comment]
Check the documentation:
https://github.com/optimistex/ngx-select-ex#api

Input | Type | Default | Description
-- | -- | -- | --
[defaultValue] | any[] | [] | Use to set default value
