### ISSUE TITLE
bad performances with large model list

### ISSUE THREAD

**Issue by Quentigus** [optimistex/ngx-select-ex#97]
Hi!

I'm having a performance issue with ~900 items.
When I click on the list to open it, I have a delay of ~2.6s under Chrome v67 (even more under IE11)

I don't :
- have the problem with the ng2-select library
- use ng-template (only optionTextField and optionValueField)

It's probably the "*ngIf" on "#choiseMenu" :
`<ul #choiceMenu role="menu" *ngIf="isFocused" class="ngx-select__choices dropdown-menu"
        [class.show]="optionsOpened">`

Thanks!

**Comment by irpanrain** [comment]
hi.. do yo have solve this problem? because me too

**Comment by optimistex** [comment]
Actually, it is not solved.

A possible solution is to render a few hundred items and use a delayed search for the others. Even if you put 1000 items into the list I believe there is no user who will read all of them. So, the user will be using the search. If he uses the search you may handle it and provide found items.

Please, let me know if such an approach works for you and you need a code example.

I close the issue. Feel free to reopen it with a request for code examples.
